### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by Luffy03** [Haochen-Wang409/U2PL#1]
Hi, are the results achieved after tta?

**Comment by Haochen-Wang409** [comment]
Of course not. Did you encounter any problems when reproducing the results?

**Comment by Luffy03** [comment]
> Of course not. Did you encounter any problems when reproducing the results?

I retrained the model and failed to get closed results for pascal dataset. Maybe I should try again. Thanks

**Comment by Luffy03** [comment]
> Of course not. Did you encounter any problems when reproducing the results?

Would you plan to share your checkpoints for pascal experiment? It will help me a lot! Thanks!

**Comment by Haochen-Wang409** [comment]
Did you use 4 GPUs with ```lr=0.001``` for training?

**Comment by Wisdom-tooth55** [comment]
When I downloaded PASCAL VOC 2012 data from the link you provided, I found that the internal structure of the folder was different from what you required. Besides, can I run the code with a single GPU?

**Comment by Haochen-Wang409** [comment]
Hi, Please refer to [this link](https://github.com/zhixuanli/segmentation-paper-reading-notes/blob/master/others/Summary%20of%20the%20semantic%20segmentation%20datasets.md) (3. VOC with SBD) for downloading the data.

In fact, yes, you can run the code with 1 GPU. But don't forget to change ```lr``` in ```config.yaml```.

**Comment by Haochen-Wang409** [comment]
Hi, @Luffy03, we re-trained our method and checkpoints are [here](https://drive.google.com/drive/folders/1_BcixhrEqJEMo3lzKTKPJ_7gCWEjUBWp?usp=sharing).
