### ISSUE TITLE
Questions about computing resouces

### ISSUE THREAD

**Issue by HeimingX** [Haochen-Wang409/U2PL#10]
Hi, thanks for the previous prompt responses. 

Today, I ran an experiment based on this repo (`u2pl/experiments/pascal/1464/ours/train.sh`) with 4 * V100 (32G/gpu) and I got an CUDA OOM error: `RuntimeError: CUDA out of memory. Tried to allocate 16.63 GiB (GPU 0; 31.75 GiB total capacity; 5.13 GiB already allocated; 16.63 GiB free; 13.83 GiB reserved in total by PyTorch)`. This error is thrown out when the program comes into second epoch, i.e., the contrastive loss term is activated.

Since the tutorial in README only mentions the number of GPU but not the capacity, I wonder how many resouces are required for U2PL? Thanks

**Comment by Haochen-Wang409** [comment]
Our U<sup>2</sup>PL is trained on 4 * ```V100 (32G)```, which is the same as yours.
I am not sure why you encounter this OOM error :(

Maybe you could try training in the ```fp16``` mode: https://github.com/NVIDIA/apex

**Comment by HeimingX** [comment]
Got it, thanks, I will have a try.

**Comment by elle-miller** [comment]
Hi @HeimingX, did you avoid the OOM error using fp16 mode? I am facing the same issue, but have 8x V100 16GB gpus. Thanks!

**Comment by Haochen-Wang409** [comment]
How about reduce the ```batch_size``` in ```config.yaml```?

**Comment by elle-miller** [comment]
Hi @Haochen-Wang409, thanks for response. Changing `batch_size` from 2 to 1 worked! Thank you very much :)

**Comment by Haochen-Wang409** [comment]
Please feel free to contact me if you have any questions :)
