### ISSUE TITLE
resnet101.pth文件寻找不到

### ISSUE THREAD

**Issue by bulindun** [Haochen-Wang409/U2PL#101]
作者您好，冒昧打扰。我在下载了resnet101.pth文件后，将其放置在u2pl/models文件夹下，resnet.py里面已经有了resnet101.pth的路径，但是train.sh运行时仍报错无法找到resnet101.pth文件：
resnet.py中的程序：
![1](https://user-images.githubusercontent.com/117715042/204993877-a7933c97-ee6f-4bc5-a7f4-169d5d90d000.png)
训练的报错信息：
![2](https://user-images.githubusercontent.com/117715042/204993944-ce8e3e85-d390-482f-8b08-9feee456fed4.png)

**Comment by Haochen-Wang409** [comment]
直接在 ```resnet.py``` 中把路径改为您保存的路径即可

**Comment by bulindun** [comment]
不好意思再次打扰。CUDNN没有初始化的问题
![4](https://user-images.githubusercontent.com/117715042/205011155-6df4279e-229a-47c3-9081-f81057ea25b9.png)
请问这是什么情况？
我的torch1.8.1，torchvision0.9.1,  cuda10.2.89,    cudnn7.6.5

**Comment by Haochen-Wang409** [comment]
一般的 cuda 训练程序是否能训练起来？比如在 MNIST 数据集用 CUDA 训练一个 ResNet-18

**Comment by Jianf-Wang** [comment]
Hi, 作者您好. 我想问一下您能提供一个resnet-50.pth的下载地址不，我 gpu memory 目前不太够， 玩不起 resnet101
