### ISSUE TITLE
Size don't match when augument

### ISSUE THREAD

**Issue by Holmes2002** [Haochen-Wang409/U2PL#102]
Hi, when I get ['pre'] from model and augument them.  
RuntimeError: The size of tensor a (57) must match the size of tensor b (224) at non-singleton dimension 1
Dimension of out don't match with real images 
Why ? Error come from decode or encoder of model ?

**Comment by Holmes2002** [comment]
It come from encoder. I print out and get shape 57 57. Shoud I adjust somethings to get suitable size ?

**Comment by Haochen-Wang409** [comment]
Sorry, I cannot fully understand what you have encountered. What does ['pre'] exactly mean?

**Comment by Holmes2002** [comment]
It is outs ['pred'] of yours

**Comment by Holmes2002** [comment]
![image](https://user-images.githubusercontent.com/73396391/205469647-d97dd018-7a87-4d0f-a183-5dce48760de8.png)

**Comment by Haochen-Wang409** [comment]
Supervised loss is computed based on ```pred_l_large``` [here](https://github.com/Haochen-Wang409/U2PL/blob/main/train_semi.py#L358).
Unsupervised loss is computed based on ```pred_u_large``` [here](https://github.com/Haochen-Wang409/U2PL/blob/main/train_semi.py#L380).

```large``` indicates the predictions are upsampled to ```HxW```.

**Comment by Holmes2002** [comment]
Tks for reply sir !

**Comment by Holmes2002** [comment]
1.How many used images for extract unreliable and for contrastive loss ?
   May be all for unreliable and 50 for contrastive(negative in your code) ?
2. Between Low rank and high rank  are classes we are concerned ?
 Hope u answer for me !

**Comment by Holmes2002** [comment]
U said that All features of Unreliable pixel were stored in a memory bank . But I search all find don't see u and them to list memory bank. Do u get from dist ? 
I run the program but contras lost rezo. I find that my memory bank is still the same as the original ( all are (0,256))
Because I can run multi gps. Can u give me an advice ?

**Comment by Haochen-Wang409** [comment]
Provide your script and log, please.

**Comment by Holmes2002** [comment]
'''
dataset: # Required.
  type: customs_semi
  train:
    data_root: /home/congvu/Semi_Segment/U2PL/data/customs
    data_list: labeled.txt
    data_LIP : LIPs.txt
    flip: True
    GaussianBlur: False
    rand_resize: [0.5, 2.0]
    #rand_rotation: [-10.0, 10.0]
    crop:
      type: rand
      size: [224, 224] # crop image with HxW size
  val:
    data_root: /home/congvu/Semi_Segment/U2PL/data/customs
    data_list: val.txt
    crop:
      type: center
      size: [224, 224] # crop image with HxW size
  batch_size: 4
  n_sup: 59549
  noise_std: 0.1
  workers: 2
  mean: [123.675, 116.28, 103.53]
  std: [58.395, 57.12, 57.375]
  ignore_label: 255

trainer: # Required.
  epochs: 200
  eval_on: True
  sup_only_epoch: 0
  optimizer:
    type: SGD
    kwargs:
      lr: 0.01  # 8GPUs
      momentum: 0.9
      weight_decay: 0.0005
  lr_scheduler:
    mode: poly
    kwargs:
      power: 0.9
  unsupervised:
    TTA: False
    drop_percent: 80
    apply_aug: cutmix
  contrastive:
    negative_high_entropy: True
    low_rank: 1
    high_rank: 9
    current_class_threshold: 0.3
    current_class_negative_threshold: 1
    unsupervised_entropy_ignore: 80
    low_entropy_threshold: 20
    num_negatives: 200
    num_queries: 256
    temperature: 0.5

saver:
  auto_resume: True
  snapshot_dir: checkpoints
  pretrain: ''

criterion:
  type: ohem
  kwargs:
    thresh: 0.7
    min_kept: 100000

net: # Required.
  num_classes: 9
  sync_bn: False
  ema_decay: 0.99
  aux_loss:
    aux_plane: 1024
    loss_weight: 0.4
  encoder:
    type: model.resnet.resnet101
    kwargs:
      multi_grid: True
      zero_init_residual: True
      fpn: True
      replace_stride_with_dilation: [False, True, True]  #layer0...1 is fixed, layer2...4
  decoder:
    type: model.decoder.dec_deeplabv3_plus
    kwargs:
      inner_planes: 256
      dilations: [12, 24, 36] '''

**Comment by Holmes2002** [comment]
![image](https://user-images.githubusercontent.com/73396391/205793650-9c0bdcaa-017e-490e-b738-5f348eaa6339.png)

what are results of dequeue_and_queue  and gather_together?

**Comment by Holmes2002** [comment]
I tried with my own and succesed about 6 months ago. I want to know the memorybank and dequue_andqueue of u

**Comment by Haochen-Wang409** [comment]
Please refer to [PyTorch documentation](https://pytorch.org/docs/stable/distributed.html?highlight=all_gather_object#torch.distributed.all_gather_object) for understanding ```dequeue_and_enqueue```.

**Comment by Holmes2002** [comment]
![image](https://user-images.githubusercontent.com/73396391/205807935-e87d066f-a4a5-4d36-b686-9e7cb2a750d5.png)
is high_valid_pixel_seg I put to memorybank  same : 
'''
        # positive sample: center of the class
        seg_proto_list.append(
            torch.mean(
                rep_teacher[low_valid_pixel_seg.bool()].detach(), dim=0, keepdim=True
            )
        )
'''
will use for negative_feat ?

**Comment by Haochen-Wang409** [comment]
```high_valid_pixel_seg``` is a binary mask to filter *unreliable* pixels (*i.e.*, negative samples), while ```low_valid_pixel_seg``` is to filter *reliable* pixels (*i.e.*, positive samples).

**Comment by Holmes2002** [comment]
how can I extract negative samples sir ?

**Comment by Haochen-Wang409** [comment]
https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/utils/loss_helper.py#L190
Please check the code ```compute_contra_memobank_loss``` **carefully**.

**Comment by Holmes2002** [comment]
Not use contrastive loss will significantly affect  to training model ?

**Comment by Haochen-Wang409** [comment]
Without contrastive loss, our method is equivalent to CutMix, which is expected to cause performance degradation.
I am not sure what *significantly* means.
