### ISSUE TITLE
自建dataset

### ISSUE THREAD

**Issue by idayulin** [Haochen-Wang409/U2PL#104]
作者您好
有几个问题想请问您
1. 请问resnet101的pre-train weight是自行训练的还是从官网下载
2. 如果想把backbone换成resnet34且使用单GPU训练2 class的任务 lr=0.000125是可行的吗
3. 若想使用customs dataset训练ground trouth可以使用只有0跟255组成的黑白mask image吗？目前这样做是失败的

谢谢您

**Comment by Haochen-Wang409** [comment]
1. 我们提供了 ResNet-101 的 pre-train 模型，请查看 README 下载
2. 应该是可行的，但是需要自行在 ImageNet-1K 上预训练一下 ResNet-34
3. 目前失败的原因可能是当前设置了 ```ignore_index=255```，您可以把 mask 改成 0-1 的 binary mask
