### ISSUE TITLE
paper question

### ISSUE THREAD

**Issue by DeepHM** [Haochen-Wang409/U2PL#107]
Below is the content of infoNCE, a contrastive learning loss in your paper (page 3) :

<img src="https://user-images.githubusercontent.com/37736774/220240138-802bd056-eea3-4fbc-a94d-7ffec7cd0a19.png" width="500" height="400">

Below is the contrastive setting of the experiments/pascal/1464/ours/config.yaml :
<img src="https://user-images.githubusercontent.com/37736774/220240727-575bd1fe-7744-4a62-ac13-afc4d7444d36.png" width="250" height="250">

According to the contrastive learning setup in your paper,
M is the number of anchor pixels, and N is the number of negative samples. (M=50, N=256)
However, in config.yaml it seems that (num_negatives is 50) and (num_queries is 256).
Regarding the infoNCE loss formula, I think it should be M=num_queries=256, N=num_negatives=50.
Am I wrong?

Also, I don't quite understand the definition of positive and negative samples in contrastive learning described in your thesis.
Can you explain positive samples and negative samples in more detail?

Thank you in advance.

**Comment by Haochen-Wang409** [comment]
Please follow the configuration provided by our code.

Positive samples $(q, k^{+})$ mean these two features (possibly) belong to the same category, and InfoNCE aims to pull them together.
Negative samples $(q, k^{-})$, on the contrary, indicate these two features (possibly) do not belong to the same category. We should push them away by minimizing InfoNCE.
