### ISSUE TITLE
function compute_contra_memobank_loss

### ISSUE THREAD

**Issue by victorshengwgit** [Haochen-Wang409/U2PL#109]
hxd，在 “”“ compute_contra_memobank_loss”“” 这个方法中current_class_negative_threshold 为啥设置为1
![image](https://user-images.githubusercontent.com/87215766/222881759-73d83199-66a0-4c27-b5a6-30c03bea0f60.png)

**Comment by Haochen-Wang409** [comment]
因为我们用熵去选负样本了，而非这里的 confidence
