### ISSUE TITLE
Have you ever tried the case of only two classes segmentation?

### ISSUE THREAD

**Issue by Wisdom-tooth55** [Haochen-Wang409/U2PL#11]
According to your article, the innovation point of the method you proposed is to use unreliable pixels as negative samples for training. For the segmentation problem with only two categories, how can unreliable pixels be trained as negative samples? It seems that unreliable pixels cannot provide negative information at this time.

**Comment by Haochen-Wang409** [comment]
Hi, this is an interesting question.

As you can see, for most semantic segmentation benchmarks (e.g., PASCAL VOC 2012, Cityscapes, and ADE-20K), the number of classes are greater than 2. 

If you really want to use our method on dataset which contains only 2 classes, I recommend you to set $r_l$ in Eq. (14) and Eq. (15) to 1.

Actually, we ablated the different value of $r_l$ in Tab. 6. If we set $r_l$ to 1, the performances slightly drop on PASCAL VOC 2012 dataset, prooving our U<sup>2</sup>PL is robust against $r_l$.
