### ISSUE TITLE
confusions about the performance of Sup-only

### ISSUE THREAD

**Issue by victorshengwgit** [Haochen-Wang409/U2PL#113]
您好，我在全监督训练过程中遇到一些问题希望请教您。
1. 在使用我自己数据集三分类（含背景）时，直接使用您提高的ResNet101，epoch = 400 调整`lr = 0.005 ` 训练时Class 1，Class 2 的IoU 基本处于43左右。您觉得这样的sup 结果适合进行下一步semi训练吗？ 或者说您觉得IoU需要优化到多少更适合进行semi的训练？ 应该如何更好的优化呢？

![sup_resnet101](https://user-images.githubusercontent.com/87215766/225805715-37a17888-f12d-4f26-8bda-14cd5dab9875.png)

2. 我也尝试了您model.py中其他模型，发现ResNet50,152 都会出现权重尺寸不匹配，如果想使用预训练，您能给我一些建议建议吗？

![微信图片_20230317113329](https://user-images.githubusercontent.com/87215766/225806236-9b3e8034-5073-448c-9b4c-16911ccfd4df.jpg)

**Comment by Haochen-Wang409** [comment]
1. 需要具体到您数据集的难度情况 (例如 class1 class2 是否都是长尾分布)，如果达到了之前全监督方法的精度，则可以考虑进行半监督训练。
2. 我们的 ResNets 针对分割进行了一定的修改。具体的修改您可以查阅相关 [issue](https://github.com/Haochen-Wang409/U2PL/issues/21)。如果需要引入 PyTorch 官方 ResNets 权重，可以将 ```self.conv1``` 更改为 ```conv7x7```，而非现在实现的多层 ```conv3x3```。

相关链接
PyTorch ResNets: https://github.com/pytorch/vision/blob/main/torchvision/models/resnet.py#L197
Our ResNets: https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/models/resnet.py#L178
