### ISSUE TITLE
How can I use resnet18 instead of resnet101? 

### ISSUE THREAD

**Issue by daeunni** [Haochen-Wang409/U2PL#115]
Hi, @Haochen-Wang409 
thanks for your nice work.
btw, due to the oom, I wanted to change resnet101 to resnet18. 

Where can I download resnet18 pretrained model? 
I encountered errors below when I used [this resnet18 model](https://github.com/fregu856/deeplabv3/tree/master/pretrained_models/resnet). 

`NotImplementedError: Dilation > 1 not supported in BasicBlock`

(I already changed `config.yaml` and `resnet path`)

**Comment by Haochen-Wang409** [comment]
Maybe you could try setting ```replace_with_dillation: [False, False, False]``` in the ```config.yaml```, since we do not implement this for R-18 and R-34.
Or, you could try to implement it by yourself based on the implementations with R-50, R-101, and R-152.

**Comment by daeunni** [comment]
Thanks a lot. 
I'll use resnet50 :)

**Comment by yang654123** [comment]
> Thanks a lot. I'll use resnet50 :)
hi， have you finished the reproduction? in classic val set?
