### ISSUE TITLE
对比学习一些参数问题

### ISSUE THREAD

**Issue by kimjisoo12** [Haochen-Wang409/U2PL#116]
感谢您这么优秀的工作，很抱歉打扰您，有一些问题想向您请教。

1. 代码中用于对比学习的特殊头，输出维度是256，请问这是否依赖于分割模型的输出特征维度或者和分割模型的特征维度什么有关系呢 还是说可以自行修改。
2. 为何在supervised_loss和unsupervised_loss均采用的是H,W尺寸计算loss，在contrast_loss中却是使用了H/4,W/4尺寸。
3. anchor_pixel和negative_pixel我可否理解为在每个batch的所有图像中每个类别分别选择了256个anchor_pixel以及50个negative_pixel，这个是否是您batchsize大小和尺寸所决定的最优解，若我的batchsize与尺寸与您不同，是否需要调整。

**Comment by Haochen-Wang409** [comment]
感谢关注与认可！
1. 输出维度可以自行修改。我们是参照了一些自监督的工作 (DINO, MoCo 等)，它们都将 backbone 输出的特征 project 到了一个较低维度，进行对比学习。
2. contrastive loss 如果也采用 HW，可能造成显存占用过大。我们当时没有对此进行消融，您可以尝试将 projector 输出的特征上采样到 HW 再计算 contrastive loss
3. 这两个参数我们是 follow 了 ReCo，也没有过多消融。这两个超参数应当与 batch_size 与 输入尺寸 均有关，应当在改变相关参数后进行消融。

**Comment by kimjisoo12** [comment]
谢谢您的回复 ，关于第一个问题是否我可以理解成说这个特征头的输入是分割网络的最后一层输出，这个特征头的输出特征维度大小我是可以自行决定。

**Comment by Haochen-Wang409** [comment]
是的，您的理解十分准确。甚至这个特征头的具体网络结构也可以自行设定，例如几层卷积、是否加BN等等

**Comment by kimjisoo12** [comment]
您好，很抱歉再打扰您一下，关于对比学习我想再请教一个问题，您文章中的网络流程图看出可靠和不可靠的像素仅存在于无标签的数据当中，那么理解下来对比学习应该也是用到无标签的数据及其伪标签，为什么在对比学习中还用到了有标签的数据及其标签？通过流程图我理解可能有标签的数据和标签只用于了有监督的loss计算。
![image](https://user-images.githubusercontent.com/89247664/230262461-bbdf2d81-2909-4207-9f62-ee72a5ef8e12.png)

**Comment by Haochen-Wang409** [comment]
该流程图想强调的是不可靠伪标签可以作为负样本，进一步利用。而有标签数据的正样本、负样本的计算很trival，因此没有在流程图体现。

**Comment by kimjisoo12** [comment]
您的意思是不是对于有标签的样本来说因为他有真实标签，在特征空间中可以非常确定的达到同类之间使其距离相近，不同类之间使其距离想斥。但对于无标签来说没有真实标签 因此通过熵的可靠性筛选使负样本一定不属于某些类，使其在特征空间中远离这些类从而达到利用的效果。不知道我理解的对不对

**Comment by Haochen-Wang409** [comment]
“在特征空间中可以非常确定的达到同类之间使其距离相近”这一点也是需要对比学习损失进行帮助。
后面一点的理解十分准确。

**Comment by kimjisoo12** [comment]
明白了 非常感谢您详细的回复 谢谢您
