### ISSUE TITLE
VOC2012 have no eval.sh

### ISSUE THREAD

**Issue by licongguan** [Haochen-Wang409/U2PL#117]
hi i have a question,
I want to evaluate the model results of VOC2012. I did not find eval.sh in the experiments/pascal/1464 path. I tried to copy the eval.sh of cityscapes and run it. I found that the result did not give mIoU in the end, but only the segmentation and visualization results.

**Comment by Haochen-Wang409** [comment]
We did not perform the sliding window evaluation for PASCAL VOC 2012. Instead, we simply report the best_miou on the validation set during the training stage.
