### ISSUE TITLE
can i

### ISSUE THREAD

**Issue by degts** [Haochen-Wang409/U2PL#118]

**Comment by degts** [comment]
您好，很抱歉打扰您，我想知道此方法在医学图像分割领域的表现怎么样呢？我在自己的数据集上跑了resnet101+deeplabv3+，效果不是很好，可以将network structure可以更换为unet吗，请问您之前是否有过这样的尝试？

**Comment by Haochen-Wang409** [comment]
可以尝试，我们之前没有类似尝试

**Comment by degts** [comment]
好的好的，感谢您的回复。
