### ISSUE TITLE
Reproducing Results for Cityscapes 

### ISSUE THREAD

**Issue by YongHakLee** [Haochen-Wang409/U2PL#120]
Hi, @Haochen-Wang409 
thanks for your nice work.

I want to reproduce results for cityscapes by using U2PL (w/ CutMix) method.
I did two experiments, but I got less than 10% mIoU on README.md  .
The GPU specifications I can use are different, so I modified some elements of config.yaml to conduct the experiment, and the following are the results according to those settings.

* Pretrained Backbone : resnet101.pth from [Google Drive] on README.md
* Dataset : Cityscapes
* Labeled Ratio 1/4 (744)

* Config.yaml
    * batch_size: 1 (I can use 2 * VRAM (24G), batch_size:2 => OOM) 
    * epochs: 67
        * by equation : 
        * the epochs of the semi-supervised = iteration/(number of unlabeled/batch size) 
        * 74400(1115.5/2) ~= 67 ( 2*GPU, total batch_size = 2)

* Results
    * lr=0.01
        * Best mIoU=60.77, Best Epoch=55
    * lr=0.01/8=0.00125
        * Since I used total batch_size=2, I experimented by dividing lr by 8.
        * by README.md, for semi-supervised learning based on (batch_size=2, 8GPU => total batch_size=16)
        * Best mIoU=67.83, Best Epoch=20

Both results are significantly lower than the 76.47 found on README.md.
What would be the problem with setting up the experiment?
How do I get a mIoU close to 76.47?
I'd really appreciate it if you could help me.
Thank you.

**Comment by Haochen-Wang409** [comment]
U2PL is trained with 200 epochs on Cityscapes. Have you tried a longer training schedule?

**Comment by YongHakLee** [comment]
I'll experiment with a longer training schedule and comment again. Thank you.

**Comment by YongHakLee** [comment]
> U2PL is trained with 200 epochs on Cityscapes. Have you tried a longer training schedule?

Thank you so much.
Based on your advice, I applied the longer training schedule and modified some settings to get results close to the mIoU on README.md .

By the way, I want to find the best mIoU among the models I trained.
We use "eval.py " for evaluation, which seems to process images one by one.
Is there an evaluation code that processes images in batch units?

I sincerely ask for your help.
Thank you.

**Comment by Haochen-Wang409** [comment]
I am happy to hear that you have successfully reproduced our results!!!

In fact, we do not provide codes of sliding window evaluation for a batch of images.
There may be a discrepancy: during training, the evaluation is conducted with a single crop of 769x769, while the sliding window evaluation is needed after training to obtain final segmentation results.
It is possible to perform SW after every epoch but it is extremely time-consuming.

**Comment by YongHakLee** [comment]
Thank you for your kind reply.
Your advice was very helpful.
I'll comment again if I need any other help.

Thank you very much!!

**Comment by YongHakLee** [comment]
Hello,
I'm sorry to ask you again.
How did you get the mIoU on README.md ? Is it correct that the best validation Epoch model obtained during the training process was evaluated as "eval.sh "?
How did you get Best mIoU if it wasn't?

Can there be other epochs that obtain a higher evaluation mIoU than the evaluation mIoU of the Best validation epoch model obtained during the training process?
So do we have to evaluate all epoch models?

**Comment by Haochen-Wang409** [comment]
For experiments on PASCAL VOC, we did not use ```eval.sh``` and simply report the best mIoU during training following AEL.
For experiments on Cityscapes, we save ```ckpt_best.pth``` for further sliding window evaluation in ```eval.sh```.

Yes, you are right. There can be other models that perform worse when evaluated under a single 769x769 crop but achieve better performance after running ```eval.sh```.
Evaluating all models for each epoch using ```eval.sh``` can avoid this issue but it is time-consuming.

**Comment by syqisme** [comment]
> > U2PL is trained with 200 epochs on Cityscapes. Have you tried a longer training schedule?
> 
> Thank you so much. Based on your advice, I applied the longer training schedule and modified some settings to get results close to the mIoU on README.md .
> 
> By the way, I want to find the best mIoU among the models I trained. We use "eval.py " for evaluation, which seems to process images one by one. Is there an evaluation code that processes images in batch units?
> 
> I sincerely ask for your help. Thank you.

Hello, I saw your inquiry on May 22nd on u2pl regarding the reproducibility issue of Cityscapes dataset results and your question to the author. I noticed you mentioned modifying some settings and adjusting the training epochs to replicate the results provided by the author. I'm currently facing a similar issue. Could you please let me know which settings you modified? Your response would be greatly appreciated.

**Comment by Haochen-Wang409** [comment]
To reproduce results on Cityscapes, please follow this configuration: https://github.com/Haochen-Wang409/U2PL/blob/main/experiments/cityscapes/744/ours/config.yaml.
