### ISSUE TITLE
对iou计算的疑惑

### ISSUE THREAD

**Issue by dengxl0520** [Haochen-Wang409/U2PL#121]
https://github.com/Haochen-Wang409/U2PL/blob/ab3d2be313d4d6b2885e7a0213d4fce82a803b79/train_semi.py#L646

如上面计算的iou，为什么是先计算某个类的交集的sum和并集的sum，再相除？
而不是分别计算每个图片的iou再求mean？
这两者差别还是蛮大的

**Comment by Haochen-Wang409** [comment]
IoU的计算定义就是要首先遍历数据集求出总的I和总的U，再相除。
