### ISSUE TITLE
您好，请问Train a Semi-Supervised Model里模型的第一个epoch是只在标注数据上训练吗？

### ISSUE THREAD

**Issue by co-br** [Haochen-Wang409/U2PL#122]

**Comment by Haochen-Wang409** [comment]
是的，当然也可以通过设置不同的 ```sup_only_epoch``` 实现不同的 epoch 数

**Comment by co-br** [comment]
非常感谢您的回复！请问这样的话第二个epoch开始直接开始预测未标注数据的伪标签并参与训练，这里面伪标签的准确率会不会很低。因为模型似乎还没开始拟合已有的标注数据。

**Comment by Haochen-Wang409** [comment]
你可以尝试调大 ```sup_only_epoch``` 以缓解这个问题

**Comment by co-br** [comment]
谢谢！请问Train a Semi-Supervised Model里面是不是只有resnet101 用的是在 ImageNet-1K上预训练好的模型，而DeepLabv3的参数则是随机初始化的？

**Comment by Haochen-Wang409** [comment]
是的

**Comment by co-br** [comment]
非常感谢您的解疑！
