### ISSUE TITLE
hello ! Execuce I want train my model with one GPU ,how can I modefiy code

### ISSUE THREAD

**Issue by yjq767579182** [Haochen-Wang409/U2PL#123]

**Comment by Haochen-Wang409** [comment]
No modification is needed. Just run ```bash train.sh 1 <port>```.

**Comment by yjq767579182** [comment]
oh！Thanks very much! But I have another question, I want to  ask about eval.py and infer.py. Will eval.py generate a visual evaluation index file, and will infer.py generate a visual segmentation file.I hope my little question didn't bother you, looking forward to your answer.

**Comment by Haochen-Wang409** [comment]
```infer.py``` will save segmentation maps and colorized maps.
For details, see https://github.com/Haochen-Wang409/U2PL/blob/main/infer.py#L130-L134

**Comment by yjq767579182** [comment]
Thanks a lot and all the best
