### ISSUE TITLE
Question about the GPU memory

### ISSUE THREAD

**Issue by Hugo-cell111** [Haochen-Wang409/U2PL#124]
Hi! In the paper the batch size is set as 16 when training with Cityscapes, but when I just set the bs as 1, the memory has come to 16517 Mb. So I wonder how many GPUs are used when training with the batch size of 16? Looking forward to your reply. Thanks!

**Comment by Haochen-Wang409** [comment]
The batch size for each GPU is 2 and we trained our model using 8 Tesla V100 (32G) GPUs.

**Comment by Hugo-cell111** [comment]
Thanks!
