### ISSUE TITLE
如果训练断掉了 怎样从断点继续训练而不是从头开始训练

### ISSUE THREAD

**Issue by yjq767579182** [Haochen-Wang409/U2PL#126]

**Comment by Haochen-Wang409** [comment]
在 ```saver``` 下面添加 ```auto_resume: True``` 即可

**Comment by yjq767579182** [comment]
ok thanks！

**Comment by yjq767579182** [comment]
I still have a question, for the encoder, can I use any feature extractor, like some mainstream transformers, and I still use deeplab or other decoders

**Comment by yjq767579182** [comment]
for the apply_aug, wherther have other choose

**Comment by Haochen-Wang409** [comment]
Of course, you can use any other backbones.
As for ```apply_aug```, we support CutOut, CutMix, and ClassMix.

**Comment by yjq767579182** [comment]
![image](https://github.com/Haochen-Wang409/U2PL/assets/64903280/b92ec379-8fd5-417c-84da-252a628ae1da)我想请问这段代码是实现了论文里的这个功能吗
![image](https://github.com/Haochen-Wang409/U2PL/assets/64903280/6b87bf62-7879-4adf-bea3-ef9ec322cfb8)

**Comment by Haochen-Wang409** [comment]
是的，对于每一个类别，我们都维护了一个 memory bank 去储存不可靠的伪标签

**Comment by yjq767579182** [comment]
oh! thanks for your answer！I'm very appreciated

**Comment by yjq767579182** [comment]
hello i'm here to ask a question again，I would like to ask if the 1 in the figure is set to 3, 4 or larger, will it have a better effect on semi-supervised，
![image](https://github.com/Haochen-Wang409/U2PL/assets/64903280/cd76bfce-951e-49ed-b435-3efb11455b5f)

**Comment by Haochen-Wang409** [comment]
You can try it. We did not ablate this.

**Comment by yjq767579182** [comment]
ok thanks

**Comment by yjq767579182** [comment]
hello，I would like to take the liberty to ask, ema_decay=0.99, so why do we need to set the teacher model and the student model? The specific gravity coefficient of 0.99 is not much different.

**Comment by yjq767579182** [comment]
![image](https://github.com/Haochen-Wang409/U2PL/assets/64903280/2acb59a7-b750-4a0b-990e-7127ad851945)
Hello author, I still have a question to ask, why does the marked data still have a threshold, as shown in the picture

**Comment by Haochen-Wang409** [comment]
> hello，I would like to take the liberty to ask, ema_decay=0.99, so why do we need to set the teacher model and the student model? The specific gravity coefficient of 0.99 is not much different.

The teacher model is used to generate pseudo-labels to supervise the student model for each unlabeled sample.

**Comment by Haochen-Wang409** [comment]
> ![image](https://user-images.githubusercontent.com/64903280/252236413-2acb59a7-b750-4a0b-990e-7127ad851945.png) Hello author, I still have a question to ask, why does the marked data still have a threshold, as shown in the picture

Features of those low confident labeled pixels might be biased.
