### ISSUE TITLE
Question about EMA

### ISSUE THREAD

**Issue by yingao123** [Haochen-Wang409/U2PL#128]
I wonder how is the teacher model initialized before doing EMA? (i.e. directly copy the parameters from the student model, randomly initialized)

**Comment by Haochen-Wang409** [comment]
In our code, the teacher is randomly initialized.

**Comment by yingao123** [comment]
> In our code, the teacher is randomly initialized.

Why not directly copy the parameters of the student model? Because at that moment, the student model has a good performance. It doesn't seem to make sense to use a randomly initialized network to supervise the student model?

**Comment by Haochen-Wang409** [comment]
Seems reasonable, but we simply followed the common practice.

**Comment by yingao123** [comment]
Thanks a lot!
