### ISSUE TITLE
Code running problems

### ISSUE THREAD

**Issue by timelovery** [Haochen-Wang409/U2PL#129]
When I train the model under experiments/cityscapes/744/ours and I type 'sh train.sh 4' in the terminal, it reports the error 
tee: 'log/seg_20230706_104127'$'\r''.txt'$'\r': No such file or directory
/train_semi.py: not found. 
how to fix this

**Comment by Haochen-Wang409** [comment]
You should ```cd experiments/cityscapes/744/ours``` first.
