### ISSUE TITLE
Question about the shape of prototype

### ISSUE THREAD

**Issue by Hugo-cell111** [Haochen-Wang409/U2PL#132]
Hi! In the code the prototype is initialized as torch.zeros(num_classes, num_queries, 1, 256), and I don't know why there is an extra shape of num_queries. I think the prototype should be set for each class, so it should be torch.zeros(num_classes, 1, 256), but I may make some misunderstanding. Could you explain it? Thanks a lot!

**Comment by Haochen-Wang409** [comment]
Each query from the same class shares the same prototype. We simply repeat them.
