### ISSUE TITLE
Question about the memory bank and the keys

### ISSUE THREAD

**Issue by Hugo-cell111** [Haochen-Wang409/U2PL#133]
Hi! In this line of [code](https://github.com/Haochen-Wang409/U2PL/blob/main/train_semi.py#L498), the memobank only serves as a parameter of the function "compute_contra_memobank_loss" and it hasn't been renewed during the training process. Plus, the parameter "new_keys" is just returned without using it. So is there any mistake here? Thanks!

**Comment by Haochen-Wang409** [comment]
The memory bank is updated using ```enqueue_and_dequeue```.
