### ISSUE TITLE
Question about the memory bottleneck

### ISSUE THREAD

**Issue by Hugo-cell111** [Haochen-Wang409/U2PL#136]
Hi! I just set batch size as 1 and the memory comes to around 16 GB. I wonder where is the memory bottleneck and which part brings so much memory burden? Thanks!

**Comment by Haochen-Wang409** [comment]
Which dataset did you use? It might be the input resolution.

**Comment by Hugo-cell111** [comment]
I use Cityscapes and the input resolution is set as 769. Have you done the ablation study of memory bank and seen whether there exists difference of memory cost?
