### ISSUE TITLE
Contrastive loss does not decrease

### ISSUE THREAD

**Issue by hweejuni** [Haochen-Wang409/U2PL#137]
Hi. I'm using U2PL with my custom dataset which has only 3 classes.
And I realised that the contrastive loss does not decrease at the range of 6~8 and I couldn't figure it out why.
What would be the problem? and also, is it a problem if the unlabeled dataset is small by comparison? Thank you.

**Comment by Haochen-Wang409** [comment]
Contrastive loss acts like a regularizer instead of an optimization objective. Therefore, it may not decrease but the performance is expected to keep increasing. 

I think it is not appropriate to make the unlabeled dataset to be small.
