### ISSUE TITLE
all unsup_loss and contrativate loss are 0

### ISSUE THREAD

**Issue by xiewende** [Haochen-Wang409/U2PL#14]
Thanks for your works!
when i run semi-supervised model on PASCAL VOC 2012 , but i got all unsup_loss and contrativate loss are 0 in the log. 
Why  is this?

**Comment by Haochen-Wang409** [comment]
Hi, could you provide the training log?

**Comment by Haochen-Wang409** [comment]
I guess it might because your training is in ```epoch 0```.
Please refer to Appendix A for details about the ```warm start epoch```.

**Comment by xiewende** [comment]
yesh
thanks for your answer.
i got it.
