### ISSUE TITLE
关于自建数据集的问题

### ISSUE THREAD

**Issue by rookie0414** [Haochen-Wang409/U2PL#140]
您好，我想问一下如果要跑自己的数据集，unlabeled图片是不是也需要像增强集那样生成轮廓的粗标注？我在run的时候发现unsample会同时输入原图以及SegmentationClassAug的图。期待您的回复。

**Comment by Haochen-Wang409** [comment]
不需要粗轮廓标注。对于无标签数据，您可以将任意形式的label输入到unsample函数中。例如全0的label

**Comment by rookie0414** [comment]
好的 十分感谢！！已经run起来了。还有一个问题想问问您，sbd数据集的轮廓对于结果会有影响吗？

**Comment by Haochen-Wang409** [comment]
如果您跑的是 1464 labeled + 9118 unlabeled，那么 SBD 数据集的轮廓对于结果应当是没有影响的
