### ISSUE TITLE
为什么把ignore_label设置为0？

### ISSUE THREAD

**Issue by jjjsyyy** [Haochen-Wang409/U2PL#143]
您好，我想问一下图像裁剪时的padding，为什么要把ignore_label设置为0？这样不会影响0类的精度吗？
https://github.com/Haochen-Wang409/U2PL/blob/ab3d2be313d4d6b2885e7a0213d4fce82a803b79/u2pl/dataset/augmentation.py#L243C7-L243C7

**Comment by Haochen-Wang409** [comment]
首先需要明确的是，您给出的代码中的 ignore_label 意义为：在图像 random crop 之后，如果裁切区域大于原图的尺寸，则此时应当给超出原图的部分打什么类别的 label。因此，由于在裁切时一般把超出图像部分填充 [0, 0, 0]，则对应的 label 应当为 0，即背景类别。

在测试阶段应当是不会发生“裁切区域大于原图尺寸”的情况，因此测试阶段应当没有影响。
