### ISSUE TITLE
For domain adaptation

### ISSUE THREAD

**Issue by tanveer6715** [Haochen-Wang409/U2PL#144]
Hi
Thank you for sharing this great work. I just want to know have you tried this method for domain adaptation? Can we used it? If yes then what will be the changes required according to your suggestions?
Thanks

**Comment by Haochen-Wang409** [comment]
I think the key challenge of domain adaptation is not the same as semi-supervised learning. Therefore, it seems that U2PL can be used in DA but I am not sure about the performance.

For DA, just modify the labeled dataset and the unlabeled dataset.

**Comment by tanveer6715** [comment]
Thanks for your response. In U2PL I guess the unlabeled data is cutmixed. However for domain adaptation can we cutmixed labeled data(source domain) into unlabeled data (target domain)?

**Comment by Haochen-Wang409** [comment]
Yes, of course we can. [1] even applied ClassMix between source images and target images.

[1] DAFormer: Improving Network Architectures and Training Strategies for Domain-Adaptive Semantic Segmentation. In CVPR 2022.

**Comment by tanveer6715** [comment]
Thank you. I am closing this issue. :)
