### ISSUE TITLE
The ablation experiment of the size of memory bank

### ISSUE THREAD

**Issue by Hugo-cell111** [Haochen-Wang409/U2PL#147]
Hi! In your code the size of the memory bank of each class is set as 10000 and the background class's is set as 30000. Have you conducted the ablation study on the size of memobank and seen what the influence is exactly? Thanks!

**Comment by Haochen-Wang409** [comment]
Since the class background usually contains more pixels than other categories, we set a larger queue. We did not ablate the exact size of each category.

**Comment by Hugo-cell111** [comment]
Thanks!
