### ISSUE TITLE
Question about the teacher model

### ISSUE THREAD

**Issue by Hugo-cell111** [Haochen-Wang409/U2PL#149]
Hi! Recently I have also tried to use student-teacher model in semi-supervised learning, and I have also met the same problem as you explained in this [issue](https://github.com/Haochen-Wang409/U2PL/issues/64). But I wonder whether it is necessary to set the teacher model as model_t = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model_t)? Thanks!

**Comment by Haochen-Wang409** [comment]
I think it could be necessary since the parameters of BN will be updated during the teacher forward by switching ```model_teacher.train()```.
