### ISSUE TITLE
对比损失的变化

### ISSUE THREAD

**Issue by Hugo-cell111** [Haochen-Wang409/U2PL#155]
你好！可以问一下你们有记录各实验中对比损失的变化曲线吗？我在做实验的时候，发现自己实现的对比损失下降非常缓慢，而且各子项的变化剧烈晃动（我的对比损失由若干项组成），所以想参考一下你们的~谢谢！

**Comment by Haochen-Wang409** [comment]
我们当时没有存储训练的 log。印象中对比损失下降的不会特别明显，它更多的是起到一个正则化项的作用，而非真正需要最小化的目标函数。

**Comment by Hugo-cell111** [comment]
也就是说即使对比损失下降不是很明显，但是消融实验中对比损失依然是有效果的吗？

**Comment by Haochen-Wang409** [comment]
是的，即使对比损失下降的不明显，但对于最终的分割结果提升还是较为显著的

**Comment by Hugo-cell111** [comment]
好的，谢谢！
