### ISSUE TITLE
Unsupervised loss is 0

### ISSUE THREAD

**Issue by tanveer6715** [Haochen-Wang409/U2PL#156]
Hi
I am training this model for my own dataset having 2 classes. However I have noticed that it unsupervised loss is zero after some epochs. I have also attached the training log. What could be the possible reason for zero unsupervised loss?
[seg_20230929_143809.txt](https://github.com/Haochen-Wang409/U2PL/files/12776505/seg_20230929_143809.txt)

**Comment by Haochen-Wang409** [comment]
Could you provide a detailed explanation of your dataset? From the provided log, it seems that the mIoU is increasing during training as expected.

**Comment by tanveer6715** [comment]
My dataset have 2 classes, background and cracks. However in the log the unsupervised loss is around zero. By comparison with the suponly, the suponly mIoU is greater then semi supervised U2PL in my case. So I thought the zero unsupervised loss may be the problem.

**Comment by Haochen-Wang409** [comment]
I guess it might be because the teacher and the student are quite similar. You could try a larger ```ema_decay```, e.g., 0.999.

**Comment by tanveer6715** [comment]
ok thank you. I will try larger ema_decay and will checked if its performance improved.
