### ISSUE TITLE
train_semi.py报错，找不到一个方法

### ISSUE THREAD

**Issue by ZhiHuiCoding** [Haochen-Wang409/U2PL#160]
<img width="928" alt="1701238641533" src="https://github.com/Haochen-Wang409/U2PL/assets/86542851/c7b77e63-ced3-432d-b702-7ed8bcdd735e">
compute_binary_memobank_loss 这个方法怎么没有定义

**Comment by Haochen-Wang409** [comment]
我们的默认配置不使用这个 loss
