### ISSUE TITLE
数据集疑问

### ISSUE THREAD

**Issue by ZhiHuiCoding** [Haochen-Wang409/U2PL#161]
![疑问](https://github.com/Haochen-Wang409/U2PL/assets/86542851/9fac1474-f874-4ea8-a414-9bf60f46e546)

已经下载了download PASCAL VOC 2012 augmented with SBD dataset.数据集，但是
![ES{ ND H)ZK(U}L~S@MI)JA](https://github.com/Haochen-Wang409/U2PL/assets/86542851/5592b2d0-4e1a-4ef5-aaa6-2c6c8b1f85bb)
打不开是正常的吗

**Comment by Haochen-Wang409** [comment]
不需要打开 __MACOSX 文件夹

**Comment by ZhiHuiCoding** [comment]
请问我可以用你们训练好的模型尝试在cpu上跑几张图片吗

**Comment by Haochen-Wang409** [comment]
可以

**Comment by ZhiHuiCoding** [comment]
可以在pycharm上运行吗，对不起，我很烦

**Comment by ZhiHuiCoding** [comment]
打扰到你们了

**Comment by Haochen-Wang409** [comment]
推荐在终端运行
