### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by ZhiHuiCoding** [Haochen-Wang409/U2PL#163]
![OT 843%P`ZMS{B9$A`NEEA7](https://github.com/Haochen-Wang409/U2PL/assets/86542851/4ac98908-a5f3-42d7-b885-1a9827d8016a)

是不是数据集下载错了，我下载了 download PASCAL VOC 2012 augmented with SBD datase

**Comment by Haochen-Wang409** [comment]
把路径尝试都改为左斜杠试试看？我目前手头没有windows，无法帮助您做验证

**Comment by ZhiHuiCoding** [comment]
数据集下载哪一个，可以看一下你们下载好的数据集吗

**Comment by ZhiHuiCoding** [comment]
我下载了**PASCAL VOC 2012 augmented with SBD**
但是它跑的时候报错似乎是少了一个文件夹
