### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by ZhiHuiCoding** [Haochen-Wang409/U2PL#164]
请问数据集可以给个明确点的链接吗，我按README下载，似乎下错了。，对不起打扰了

**Comment by Haochen-Wang409** [comment]
能否更具体的描述一下您的问题，之前看到您提出少了一个文件夹，具体是少了哪个文件夹？

**Comment by Haochen-Wang409** [comment]
能否提供目前您数据集的目录情况？

**Comment by ZhiHuiCoding** [comment]
可以

**Comment by ZhiHuiCoding** [comment]
![@ GC@VO2L2T8J)6B2BF8C1G](https://github.com/Haochen-Wang409/U2PL/assets/86542851/1dbe378f-c04a-443c-9e5b-4cf0b836e190)
我根据这个链接下载了数据，然后解压目录结构如下
![H0%@CL`G0PSQ@FPVQSGS3HY](https://github.com/Haochen-Wang409/U2PL/assets/86542851/a23f4a37-8441-419b-8b61-7479edeb5b18)

**Comment by ZhiHuiCoding** [comment]
通过This download link is provided by: https://github.com/DrSleep/tensorflow-deeplab-resnet
这条链接下载的

**Comment by Haochen-Wang409** [comment]
把SegmentationClassAug文件放到上一层，并且截图该文件夹的下面的子目录

**Comment by ZhiHuiCoding** [comment]
data/VOC2012
├── Annotations
├── ImageSets
├── JPEGImages
├── SegmentationClass
├── SegmentationClassAug
└── SegmentationObject
我看你们的目录结构是这样的，但我下载的没有JPEGimages目录

**Comment by ZhiHuiCoding** [comment]
![BA%T)PQ~`Z@U%L2} Z575X9](https://github.com/Haochen-Wang409/U2PL/assets/86542851/0eeb0da3-68d7-4657-914e-67243f6e7156)
已经修改了

**Comment by ZhiHuiCoding** [comment]
你们还在回答，太感动了

**Comment by Haochen-Wang409** [comment]
那个文件夹只有label，原始的数据需要额外下载，参考：http://host.robots.ox.ac.uk/pascal/VOC/voc2012/#data

祝您科研顺利

**Comment by ZhiHuiCoding** [comment]
太谢谢你们了
