### ISSUE TITLE
损失函数缺乏定义

### ISSUE THREAD

**Issue by ZhiHuiCoding** [Haochen-Wang409/U2PL#165]
**对不起，百忙之中打扰**
<img width="547" alt="1701586725480" src="https://github.com/Haochen-Wang409/U2PL/assets/86542851/9a5df6e8-0355-44cc-a447-2bae7e1ce6fa">

**train_semi.py**  **469**行报红，该方法**compute_binary_memobank_loss**没有从loss_help.py中引入，并在loss_help.py中也没有该方法的定义

上次咨询过，您说是没有使用该方法，我一直有点不理解，不使用，报红没犯法运行呀！！！求解

**Comment by Haochen-Wang409** [comment]
注释掉这部分的代码即可

**Comment by ZhiHuiCoding** [comment]
对不起，我刚才测试了一下，python基础不扎实，原来只要没有运行到报错代码，整体代码可以运行的。我以为会有预编译呢
