### ISSUE TITLE
How to split the datasets (cityscapes) into labeled and unlabeled?

### ISSUE THREAD

**Issue by ywher** [Haochen-Wang409/U2PL#168]
Hi, nice work and I am going to reproduce the experimental results.
I want to know how you split the dataset into the labeld and unlabeled parts?
Is it random extraction or are there some rules, such as the sample selection method used in active learning?
Looking forward for you reply! Thank you!

**Comment by Haochen-Wang409** [comment]
Random selection is applied for cityscapes.

**Comment by ywher** [comment]
Ok, thanks for your reply!

> Random selection is applied for cityscapes.
