### ISSUE TITLE
Apply your work to two-class problems？

### ISSUE THREAD

**Issue by xiewende** [Haochen-Wang409/U2PL#17]
Thank you for your work .
Now I use your method to train on my dataset, but my dataset has only one class, just need to distinguish foreground and background.
When I set my num_classes=2 to training ,  but i got all contrastive loss is 0，why？
In your code ，two-class contrastive loss （compute_binary_memobank_loss）is miss，could you provide it？

**Comment by Haochen-Wang409** [comment]
Hi, ```compute_binary_memobank_loss``` is not used to compute loss_contra when ```num_classes=2```. Please refer to  Appendix C for details.

If you want to use our U<sup>2</sup>PL under a 2-class distinguish task, just change ```low_rank``` in ```config.yaml``` to 1. We have ablated the ```low_rank``` on PASCAL VOC 2012 (see Tab. 5) and our U<sup>2</sup>PL is quite robust against different ```low_rank``` and ```high_rank```.

**Comment by Haochen-Wang409** [comment]
By the way, a similar issue could be find at: https://github.com/Haochen-Wang409/U2PL/issues/11

**Comment by xiewende** [comment]
ok，thank for your answers，i solve this problem
