### ISSUE TITLE
using unreliable pixels as a basis for the selection of negative samples?

### ISSUE THREAD

**Issue by CuberrChen** [Haochen-Wang409/U2PL#18]
Am I right in thinking that the core of the paper lies in using unreliable pixels(```
1[H(pij) > γt]```) as a basis for the selection of negative samples for contrastive learning or negative learning? Because I note that Table 4 indicates the implication that adding this filtering rule improves the metric.

**Comment by CuberrChen** [comment]
![图片](https://user-images.githubusercontent.com/44107003/160354766-31fa6bd1-f972-4383-a751-038b427c80d6.png)
![图片](https://user-images.githubusercontent.com/44107003/160355139-94ee967e-8676-4de7-9bb6-bcd17ea858cc.png)
![图片](https://user-images.githubusercontent.com/44107003/160355342-eb01b8fc-5fc4-46a4-b256-a5440346d55c.png)

We can see that without adding this filtering rule, the metrics are pretty much the same as just adding contrastive loss.

**Comment by Haochen-Wang409** [comment]
Yeah, you are right.
We argue that model can be benefit from unreliable pseudo-labels a lot, which means only when we use unerliable pseudo-labels (```1[H(p) > gamma_t]```) in contrastive learning can boost the performance by a large margin.
