### ISSUE TITLE
关于伪标签过滤问题

### ISSUE THREAD

**Issue by qdd1234** [Haochen-Wang409/U2PL#2]
作者您好，感谢您精彩的工作，有两个问题想请教 您一下：
（1）通过置信度和熵值过滤噪声伪标签，这两种方式哪个更适合半监督语义分割？
（2）关于您下图中过滤伪标签阈值的确定，按照您paper中所示，通过np.percentile函数选出一定比例的伪标签，但是在训练的初期，会不会存在生成的伪标签大部分noisy的，这样反而会影响训练。是不是得先设置一个熵的阈值，当阈值低于这个阈值时候再用您paper中方式进行过滤伪标签会更好些，这仅是我看完您paper后一些想法，和您交流一下。
![image](https://user-images.githubusercontent.com/68497831/157696185-4b5283c4-d952-496e-b71f-5a69f8ea9366.png)

**Comment by Haochen-Wang409** [comment]
您好，感谢您对我们工作的支持！
（1）个人认为对于伪标签的筛选，用熵或者置信度的两种方法没有本质的区别，都假设了“模型更自信的标签更可靠”。
（2）训练初期伪标签可靠性的问题十分有趣，您所提及的“训练前期设置一个阈值，训练后期使用比例进行筛选”是一个可行的方案，应该能缓解初期训练噪声的影响。
对于该问题，我们使用了“热启动”的方法（具体可参见 Appendix 中的训练细节），即在前几个 epoch 只用有标签数据进行监督，之后再将无标签数据纳入 loss 的计算。
