### ISSUE TITLE
训练cityspace的问题

### ISSUE THREAD

**Issue by licongguan** [Haochen-Wang409/U2PL#20]
非常感谢作者的工作！
我在训练时发现 调用cityscapes/gtFine/train/bochum/bochum_000000_022210_gtFine_labelTrainIds.png，而下载的原版cityspace数据集当中只有bochum_000000_000313_gtFine_color.png，bochum_000000_000313_gtFine_instanceIds.png，bochum_000000_000313_gtFine_labelIds.png， bochum_000000_000313_gtFine_polygons.json这四种后缀格式的文件，并没有labelTrainIds.png这种，请问有解决方法吗？另外单卡也可以使用sh train.sh训练吗

**Comment by Haochen-Wang409** [comment]
关于 Cityscapes 的图片名称问题，可以参考 Issue https://github.com/Haochen-Wang409/U2PL/issues/13

单卡训练 U<sup>2</sup>PL 是可以的，同步调整 ```config.yaml``` 中的 ```lr``` 即可。
