### ISSUE TITLE
Train the model with ResNet-50 backbone

### ISSUE THREAD

**Issue by yichen928** [Haochen-Wang409/U2PL#21]
Hello, thank you for this nice work!
I am trying to train it with ResNet-50 backbone. However, I found that your code cannot load the ImageNet pretrained backbone from torchvision (https://download.pytorch.org/models/resnet50-0676ba61.pth). The pretrained ResNet-101 model from torchvision cannot work as well.

I am wondering what is the difference between your pretrained model and that provided by torchvision.

**Comment by Haochen-Wang409** [comment]
Hi, thanks for your approval of our work!

Actually, our ResNet models are a little bit different from the origin one, and we modified ResNet follow previous SOTA [AEL](https://github.com/hzhupku/SemiSeg-AEL).

As you can see in https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/models/resnet.py#L179, the first ```conv``` block of our ResNet maps 3 channels image to features with 64 channels with ```conv3x3```, while the officail ResNet adropts ```conv7x7``` (see https://github.com/pytorch/vision/blob/main/torchvision/models/resnet.py#L195).

To further understand different ResNets, please refer to [Bag of Tricks for Image Classification with Convolutional Neural Networks](https://openaccess.thecvf.com/content_CVPR_2019/papers/He_Bag_of_Tricks_for_Image_Classification_with_Convolutional_Neural_Networks_CVPR_2019_paper.pdf).

**Comment by yichen928** [comment]
Thank you very much for this helpful reply. I have solved this problem.

**Comment by yichen928** [comment]
> @yichen928 can you explain what exactly you did to use a resnet50 backbone? I am running into the same problem as you - the official resnset50 pre-trained weights don't match (in file format or shape, I'm not sure)

Sorry, I did not see your reply to this issue. You can find the ckpt of pretrained resnet50 by searching the name "resnet50-ebb6acbb.pth" with Google.  You also need to change the backbone from resnet101 to resnet50 in the config file.
