### ISSUE TITLE
训练过程出现的问题

### ISSUE THREAD

**Issue by licongguan** [Haochen-Wang409/U2PL#23]
您好，在训练过程中我使用 sh train.sh 1 0 报错，subprocess.CalledProcessError: Command '['/home/glc/anaconda3/envs/torch1.8/bin/python', '-u', '../../../../train_sup.py', '--local_rank=0', '--config=config.yaml', '--seed', '2', '--port', '0']' returned non-zero exit status 1.
我不知道port 指的是什么？ 需要根据什么信息设置？ 另外单卡时 可以不采用train.sh  可以直接用train_sup.py训练吗？

**Comment by Haochen-Wang409** [comment]
```port``` 代表分布式训练实验的端口号，建议使用大于 10000 的端口号
由于我默认采用了多卡的设置，所以单卡也需要 ```train.sh``` 中的 ```python -m torch.distributed.launch```，而不是简单地 ```python ../../../../train_sup.py```
