### ISSUE TITLE
About the structure of deeplabv3+

### ISSUE THREAD

**Issue by jianlong-yuan** [Haochen-Wang409/U2PL#25]
The model structure of deeplabv3+ in U2PL is different from the standard. Have you ever experimented with the same structure as deeplabv3+ ?

**Comment by Haochen-Wang409** [comment]
Are there any differences between our model and the official one except for the representation head?

**Comment by jianlong-yuan** [comment]
Acutally, your head is based conv, however, official head is based sep conv. In addition, your backbone has multi grid at the last stage. Generally, these difference will help your baseline much better.
