### ISSUE TITLE
About training accuracy

### ISSUE THREAD

**Issue by HeQibin** [Haochen-Wang409/U2PL#26]
I repeated experiments on U2PL according to your settings for many times, and the accuracy in the paper can not be achieved under the condition of eight V100. Can you provide the training log to help check details?

**Comment by Haochen-Wang409** [comment]
On which dataset?

**Comment by HeQibin** [comment]
Thanks for providing checkpoint, but I'm more concerned about whether the semi-supervised training can achieve the same accuracy through U2PL.

> On which dataset?

Cityscapes.

**Comment by Haochen-Wang409** [comment]
On Cityscapes dataset, we apply slide-window evaluation following [AEL](https://github.com/hzhupku/SemiSeg-AEL), which means we should run ```sh eval.sh``` after training.
Therefore, the mIoU reported during training is not the final performance, which is quite different from VOC.

Did you run ```sh eval.sh``` after training?

**Comment by Haochen-Wang409** [comment]
For instance, under 1/2 partition protocol on Cityscapes, the final result is 79.12 with AEL, but the mIoU is around 75 during training.

**Comment by Haochen-Wang409** [comment]
By the way, can you reproduce the results on VOC?

**Comment by HeQibin** [comment]
> For instance, under 1/2 partition protocol on Cityscapes, the final result is 79.12 with AEL, but the mIoU is around 75 during training.

Thanks. I'll try eval.sh.
