### ISSUE TITLE
problem of num_class=1?

### ISSUE THREAD

**Issue by xiewende** [Haochen-Wang409/U2PL#28]
nice works
When i set num_classes=1 in config file  , can i continue to use compute_contra_memobank_loss？

[](https://s3.bmp.ovh/imgs/2022/04/13/949b96f8a54adf02.jpg)

**Comment by Haochen-Wang409** [comment]
Only 1 class? Maybe you want to ask ```num_classes=2```?

**Comment by Haochen-Wang409** [comment]
If so, please refer to https://github.com/Haochen-Wang409/U2PL/issues/17 and https://github.com/Haochen-Wang409/U2PL/issues/11

**Comment by xiewende** [comment]
yes，thanks
