### ISSUE TITLE
is it a mistake in config?

### ISSUE THREAD

**Issue by CuberrChen** [Haochen-Wang409/U2PL#31]
hi, i find a diff between paper and your config.yml. num_queries(`N`) in paper is 50, num_negatives(`M`) in paper(section 3.1) is 256. but in your config file, they are contrary, as follow:
```
    num_negatives: 50
    num_queries: 256
    temperature: 0.5
```

did I understand something wrong?

**Comment by Haochen-Wang409** [comment]
Oh, thanks for finding out this mistake. We will have a double check and find out which one is the correct setting.

**Comment by Haochen-Wang409** [comment]
The config is right, please follow the config to reproduce all results.
