### ISSUE TITLE
模型的训练问题

### ISSUE THREAD

**Issue by TangYJ1229** [Haochen-Wang409/U2PL#34]
![image](https://user-images.githubusercontent.com/79182380/166103952-d6587a40-ad7d-4771-836e-648a6676a595.png)
你好，我在模型训练的时候碰到这个问题，根据报错的位置检索，发现是教师模块的模型出现了问题，但学生模块的模型和教师模块在结构上和输入上是一样的，为什么只有教师模块的模型报错呢

**Comment by Haochen-Wang409** [comment]
您使用的是 ```train.sh``` 还是 ```slurm_train.sh```？是否有修改 ```batch_size```？使用的是几张 GPU 训练？

**Comment by TangYJ1229** [comment]
我运行的是train.sh，用的一张显卡，不过我的数据量都改小了，然后没用voc的那个增强版数据集，用的原始1464张的那个数据集，分成了label与unlabel

**Comment by Haochen-Wang409** [comment]
您可以提供您训练使用的 ```config.yaml``` 嘛？

**Comment by Haochen-Wang409** [comment]
也许是因为您只用了一张显卡，而我们的代码中默认开启了 ```sync_BN```，不知道是否是这个原因（因为报错在 bn 上）。您可以尝试使用两张显卡训练？

**Comment by Haochen-Wang409** [comment]
或者您可以尝试把这两行注释掉，以使用一张显卡进行训练：
https://github.com/Haochen-Wang409/U2PL/blob/main/train_semi.py#L88-L89

**Comment by TangYJ1229** [comment]
我刚刚尝试了一下注释您说的那两行程序，不过并没有效果，因为我不太方便上传程序，我把config的截图放在下方了
![image](https://user-images.githubusercontent.com/79182380/166107437-1f0fde6a-ffa3-47ba-835e-4d5a70be2608.png)
![image](https://user-images.githubusercontent.com/79182380/166107456-bc6e1ff8-342e-4b82-8cf4-306878f29a8b.png)

**Comment by Haochen-Wang409** [comment]
您是否可以尝试使用大于一张显卡训练？

**Comment by TangYJ1229** [comment]
不好意思，我只有一张显卡，不能尝试多张显卡训练，我通过查阅这个问题，了解到这个bug可能是由于数值越界产生的，但我想不明白哪里可以产生越界

**Comment by TangYJ1229** [comment]
不好意思，我只有一张显卡，不能尝试多张显卡训练，我通过查阅这个问题，了解到这个bug可能是由于数值越界产生的，但我想不明白哪里可以产生越界

**Comment by Haochen-Wang409** [comment]
您可以尝试把所有运算转移到CPU上后再看看报错信息？

**Comment by TangYJ1229** [comment]
好的，我去试一下，感谢您的回答
