### ISSUE TITLE
模型的运行问题

### ISSUE THREAD

**Issue by Orchidbean** [Haochen-Wang409/U2PL#35]
我的服务器配置是这样的，然后我按照环境是按照readme文档上来的，为什么输入运行命令会没有反应呢
![D@E_SVD VV`BF} BJ1$ F37](https://user-images.githubusercontent.com/39043696/167254924-13e21a3b-a312-4365-b38a-6e510802e15d.png)

![KWKC@)PJB_QH4L4Y@8MPD}8](https://user-images.githubusercontent.com/39043696/167254930-9afe0f28-c3dc-4e62-aee5-c2acb4d156ea.png)

![MGFM1(}`(A95O$XW~~@R3BH](https://user-images.githubusercontent.com/39043696/167254933-1b1f81ec-4fdf-4b74-9d5e-8a5894bc5ed9.png)

**Comment by Haochen-Wang409** [comment]
请问您“没有反应”具体指的是什么情况？是输入这一行命令然后敲了回车，但程序没有运行嘛？

**Comment by Orchidbean** [comment]
是的呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haochen-Wang409/U2PL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月7日(星期六) 晚上8:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haochen-Wang409/U2PL] 模型的运行问题 (Issue #35)





 
请问您“没有反应”具体指的是什么情况？是输入这一行命令然后敲了回车，但程序没有运行嘛？

**Comment by Orchidbean** [comment]
是的

**Comment by Haochen-Wang409** [comment]
如果直接运行：
```python ../../../../train_sup.py --config=config.yaml --seed 2 --port 12345```
程序会执行嘛

**Comment by Orchidbean** [comment]
执行了，现在有另外的问题，我先去解决一下，谢谢啦~非常感谢！！！
