### ISSUE TITLE
The number of num_negatives and num_queries

### ISSUE THREAD

**Issue by Wu0409** [Haochen-Wang409/U2PL#38]

**Comment by Wu0409** [comment]
作者您好！
我想请教一下您论文中M和N的问题，我在阅读您论文的时候发现论文中的M（num_queries）为50，而N（num_negatives）为256，为什么您在代码的实现过程中，两个参数是相反的呢？

**Comment by Haochen-Wang409** [comment]
感谢关注！请以代码为主~
