### ISSUE TITLE
Missing "aux_loss" flag in config.yaml of "pascal/1464/ours" folder

### ISSUE THREAD

**Issue by HeimingX** [Haochen-Wang409/U2PL#4]
Hi, thanks for the code sharing and I just found the problem as mentioned in the title, could you please have a double check and share the complete config file? thanks

**Comment by HeimingX** [comment]
sorry for misunderstanding, it seems that the `aux loss` is not a necessary term in your method

**Comment by Haochen-Wang409** [comment]
For pascal VOC 2012, we do not use ```aux_loss```.
