### ISSUE TITLE
显存问题

### ISSUE THREAD

**Issue by Duanjiayu** [Haochen-Wang409/U2PL#41]
感谢分享代码！请问数据集使用Cityscapes，训练半监督模型需要多少显存？我单卡训练（Tesla P40），显存22.38 G，batchsize2，lr=0.00125，按照其他issues里说的，因为单卡训练所以屏蔽了train_semi.py里的相关代码：
    # if cfg.get("sync_bn", True):
    #     model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)

刚开始训练就爆显存了，训练时卡上没有跑其他模型，想问一下是我设置的问题还是有其他问题？

报错：
RuntimeError: CUDA out of memory. Tried to allocate 146.00 MiB (GPU 0; 22.38 GiB total capacity; 21.32 GiB already allocated; 79.56 MiB free; 21.53 GiB reserved in total by PyTorch)

**Comment by Haochen-Wang409** [comment]
您可以尝试一下把 batch_size 改为 1 试试看？这个保存应该就是表示 22.38G 的显存不够。
我们的实验是在 32G 显存下完成的。

**Comment by Duanjiayu** [comment]
好的，感谢您的解答

**Comment by JoyHuYY1412** [comment]
> 您可以尝试一下把 batch_size 改为 1 试试看？这个报错应该就是表示 22.38G 的显存不够。 我们的实验是在 32G 显存下完成的。

您好，请问您有统计过模型的memory和inference flip信息吗？ 想做一下比较~ 万分感谢！

**Comment by Haochen-Wang409** [comment]
抱歉，我们没有进行这类的统计。
