### ISSUE TITLE
about unsupervised_loss

### ISSUE THREAD

**Issue by xiewende** [Haochen-Wang409/U2PL#43]
![image](https://user-images.githubusercontent.com/46392987/169828391-1d946d57-ea2e-4c21-8d40-95f20c0d61f1.png)

i run VOC dataset with 1464 unlabel，the unsupervised_loss is not a gradual reduction，Is this normal ? Or what do you think went wrong？

**Comment by Haochen-Wang409** [comment]
You should change ```lr``` to ```0.0005``` if you want to train U2PL with only 2GPUs for semi-VOC.

**Comment by xiewende** [comment]
OK，i try it

**Comment by xiewende** [comment]
unfortunately，
i run with 2 3090 GPUS and lr=0.0005，but the result is similar to above！
![image](https://user-images.githubusercontent.com/46392987/169927212-44378f59-bd86-4793-8ee7-82cebc8dcd5b.png)

**Comment by Haochen-Wang409** [comment]
How about the mIoU of the model?

**Comment by xiewende** [comment]
![image](https://user-images.githubusercontent.com/46392987/169927495-25560f12-b1f0-40d2-810e-8727e96d0372.png)

but it is running now

**Comment by Haochen-Wang409** [comment]
I guess since you only have run 13 epochs, unstability of unsupervised loss becomes reasonable.

**Comment by xiewende** [comment]
Then I'll wait for it to finish and see the result
