### ISSUE TITLE
代码训练问题

### ISSUE THREAD

**Issue by FrankYii1** [Haochen-Wang409/U2PL#45]
首先，感谢您精彩的工作，我有一个问题想要请教一下您。
我使用您的代码运行了ISPRS的遥感数据集，在运行过程中碰到了一个问题：
<pre>[Info] Load ImageNet pretrain from &apos;/home/qyc/MyProject/U2PL-main/path/to/resnet101.pth&apos; 
missing_keys:  [] 
unexpected_keys:  [&apos;fc.weight&apos;, &apos;fc.bias&apos;]
[2022-05-24 22:03:30,950][    INFO] # samples: 562
[2022-05-24 22:03:30,950][    INFO] # samples: 112
[2022-05-24 22:03:30,950][    INFO] Get loader Done...
=&gt; loading checkpoint &apos;/home/qyc/MyProject/U2PL-main/path/to/resnet101.pth&apos;
Traceback (most recent call last):
  File &quot;../../../../train_sup.py&quot;, line 316, in &lt;module&gt;
    main()
  File &quot;../../../../train_sup.py&quot;, line 130, in main
    load_state(cfg[&quot;saver&quot;][&quot;pretrain&quot;], model, key=&quot;model_state&quot;)
  File &quot;/home/qyc/MyProject/U2PL-main/u2pl/utils/utils.py&quot;, line 597, in load_state
    state_dict = checkpoint[key]
KeyError: &apos;model_state&apos;
Traceback (most recent call last):
  File &quot;/home/qyc/anaconda3/envs/pytorch/lib/python3.7/runpy.py&quot;, line 193, in _run_module_as_main
    &quot;__main__&quot;, mod_spec)
  File &quot;/home/qyc/anaconda3/envs/pytorch/lib/python3.7/runpy.py&quot;, line 85, in _run_code
    exec(code, run_globals)
  File &quot;/home/qyc/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/distributed/launch.py&quot;, line 260, in &lt;module&gt;
    main()
  File &quot;/home/qyc/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/distributed/launch.py&quot;, line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command &apos;[&apos;/home/qyc/anaconda3/envs/pytorch/bin/python&apos;, &apos;-u&apos;, &apos;../../../../train_sup.py&apos;, &apos;--local_rank=0&apos;, &apos;--config=config.yaml&apos;, &apos;--seed&apos;, &apos;2&apos;, &apos;--port&apos;, &apos;23500&apos;]&apos; returned non-zero exit status 1.
</pre>

**Comment by FrankYii1** [comment]
感谢您的回复，我是在尝试使用U2PL加载预训练的Resnet模型，但不知为何发生了错误。

**Comment by Haochen-Wang409** [comment]
加载 ResNet 预训练模型只需要修改：https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/models/resnet.py#L16-L22，不需要在 ```config.yaml``` 中修改 ```pretrain``` 字段。
```pretrain``` 字段是用于加载 U2PL 预训练模型的（如 finetune）
