### ISSUE TITLE
表示头g的训练

### ISSUE THREAD

**Issue by leahyyy** [Haochen-Wang409/U2PL#46]
想请问一下，为什么需要一个表示头g对特征做进一步映射呢？跟直接在编码器的输出特征图上算对比损失有什么不一样呢？
而且表示头是随机初始化的，训练过程中只有对比损失会在这个分支更新参数是吗？怎样保证表示头朝着正确的方向在更新参数呢？

**Comment by Haochen-Wang409** [comment]
1. 对特征使用表征头 g 做映射，是参考了自监督领域的一些设计（如 SimCLR），而半监督中，ReCo 也使用了表征头
2. 我们没有做不使用 g 的实验，您有兴趣可以尝试
3. 训练过程中只有对比学习的损失会经过表征头反向传播
4. 这个问题我不是特别明白您的意思，梯度反向传播一般就会使 loss 越来越小吧

**Comment by leahyyy** [comment]
> 

不使用g的特征图我可以理解通过解码器之后计算和真值计算交叉熵损失，特征像素可以和标签像素一一对应，但是通过一个随机初始化的g之后，怎么保证特征像素和标签像素的对应关系呢

**Comment by Haochen-Wang409** [comment]
您指的是 g 输出的 feature map 和真值标签，由于它是随机初始化，可能会存在像素错位的情况嘛？

**Comment by leahyyy** [comment]
> 
编码器的输出特征图是包含语义信息的特征图，经过g之后，被一个随机初始化的映射层编码了，特征图本身的语义信息会不会被破坏掉了呢

**Comment by Haochen-Wang409** [comment]
应该问题不大。因为 g 和 f 其实都是随机初始化的全卷积层，如果 f 能训练好的话，g 应该也可以训练好。语义信息应该不会被破坏。

**Comment by leahyyy** [comment]
> 应该问题不大。因为 g 和 f 其实都是随机初始化的全卷积层，如果 f 能训练好的话，g 应该也可以训练好。语义信息应该不会被破坏。

好的，我好像明白了点，g的输出也利用到了标签信息去算对比损失，g的参数更新还是包含了语义信息的吧。
还有一个问题想问，论文中图A2的特征t-SNE展示的是网络哪一层的特征呢？

**Comment by Haochen-Wang409** [comment]
展示的是 backbone 输出的特征
