### ISSUE TITLE
eval on pascal voc

### ISSUE THREAD

**Issue by xyf159** [Haochen-Wang409/U2PL#48]
Could you  provide the test code on PASCAL VOC? Or how do I get miou after PASCAL training.

**Comment by Haochen-Wang409** [comment]
After each epoch, we will report last mIoU and best mIoU on validation set.
We report the best validation mIoU, which is a common practice in SSL-Seg.

**Comment by xyf159** [comment]
Thanks for your reply, this solved my problem.

**Comment by licongguan** [comment]
How to evaluate VOC2012 after the training is completed?

**Comment by Haochen-Wang409** [comment]
We simply report the ```best_miou``` for validation during the training stage.
