### ISSUE TITLE
Did you train resnet101 from scratch yourself in order to obtain the encoder weights?

### ISSUE THREAD

**Issue by cpsiff** [Haochen-Wang409/U2PL#49]
Hello, great work, and thanks for sharing it!

I'm trying to train U2PL with a lighter version of resnet as encoder. I see that others have wanted to do the same (#37, #21). I understand that your version of resnet is slightly modified from the official version, so the weights for the official can't be used.

I'm wondering then where you got the weights for resnet101, did you train it from scratch yourself? Additionally, did you write the entire resnet.py code just for this project, or is it borrowed from somewhere? It's strange that resnet.py seems to have support for resnet50, 34, and 18 despite those sizes not being used for U2PL.

Thank you!

**Comment by Haochen-Wang409** [comment]
Hi, thanks for attention of our work.

Actually, our implementation is based on [AEL](https://github.com/hzhupku/SemiSeg-AEL), and the pretrained resnet101 is borrowed from them.

By the way, I believe that when using the official ResNets, it will achieve similar performances.
