### ISSUE TITLE
关于对比训练

### ISSUE THREAD

**Issue by NJNUCS** [Haochen-Wang409/U2PL#51]
您好，谢谢你做出的贡献，我阅读了你的代码，发现对比学习在监督学习开始一轮后就进行了，我好奇为什么不能监督学习先训练一段时间，再加入对比学习进行训练

**Comment by Haochen-Wang409** [comment]
可以的，您可以修改 ```config.yaml``` 中的 ```sup_only_epoch``` 字段

**Comment by NJNUCS** [comment]
您好，您们的结果是基于监督学习一轮之后就进行对比学习嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haochen-Wang409/U2PL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月11日(星期六) 晚上7:23
***@***.***&gt;;
抄送:&nbsp;"완 \(ˆoˆ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haochen-Wang409/U2PL] 关于对比训练 (Issue #51)





 
可以的，您可以修改 config.yaml 中的 sup_only_epoch 字段

**Comment by Haochen-Wang409** [comment]
是的

**Comment by NJNUCS** [comment]
好滴，谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haochen ***@***.***&gt;; 
发送时间: 2022年6月11日(星期六) 晚上7:27
收件人: ***@***.***&gt;; 
抄送: "완 \(ˆoˆ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Haochen-Wang409/U2PL] 关于对比训练 (Issue #51)





 
是的
