### ISSUE TITLE
正例的计算问题

### ISSUE THREAD

**Issue by icemy** [Haochen-Wang409/U2PL#58]
非常优秀的paper和code
有个疑问，代码中
seg_proto_list.append(
            torch.mean(
                rep_teacher[low_valid_pixel_seg.bool()].detach(), dim=0, keepdim=True 
            )
 计算正例使用的mask是  low_valid_pixel_seg，而根据前面计算low_valid_pixel_seg过程，其只是低熵的mask，并没有满足论文公式9,10中的pij(c) > δp
根据我对论文和代码的理解，或许应该使用 rep_mask_low_entropy = (
            prob_seg > current_class_threshold
        ) * low_valid_pixel_seg.bool()
这个mask来计算正例？还是我理解出现偏差了。

**Comment by Haochen-Wang409** [comment]
感谢关注！

请以代码为准。当然，您可以尝试使用您的方法进行正样本特征的计算。根据经验，这应该不会带来过大的结果波动。因为 ```delta_p``` 的值较小，一般来说排名在前 20% 低熵的像素，都能满足这个要求

**Comment by icemy** [comment]
> 感谢关注！
> 
> 请以代码为准。当然，您可以尝试使用您的方法进行正样本特征的计算。根据经验，这应该不会带来过大的结果波动。因为 `delta_p` 的值较小，一般来说排名在前 20% 低熵的像素，都能满足这个要求

感谢

**Comment by NJNUCS** [comment]
您好，抱歉打扰你，我将您的对比损失用在我的代码中，使用分布式训练，表示头的梯度每次接收不到，Parameters which did not receive grad for rank 2: head.0.weight, head.1.weight, head.1.bias, represent.0.weight, represent.0.bias, represent.1.weight, represent.1.bias, represent.3.weight, represent.3.bias，我查询资料，发现模型的forward输出的张量需要进行损失计算，才能梯度回传，我使用的是您的代码，学生模型产生的特征表示用于对比计算损失，损失梯度总是回传不了，能帮我解答一下嘛，谢谢

**Comment by Haochen-Wang409** [comment]
您训练的是半监督模型还是全监督的 SupOnly 模型呢？能够提供一下 log 嘛

**Comment by NJNUCS** [comment]
你好，我是使用的是半监督的模型，我就是想用你的对比损失，因为网络中没有表示头，我自己创建了一个表示头：
self.represent = nn.Sequential(
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; nn.Conv2d(512,256,kernel_size=3,padding=1,dilation=1,bias=False),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; nn.SyncBatchNorm(256),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; nn.ReLU(inplace=True),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; nn.Conv2d(256,256,kernel_size=3,stride=1,padding=1,bias=True),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; nn.SyncBatchNorm(256),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; nn.ReLU(inplace=True),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; nn.Conv2d(256,256,kernel_size=1,stride=1,padding=0,bias=True)
&nbsp; &nbsp; &nbsp; &nbsp; )

网络forward了这个表示头和预测结果，但是，我在训练的过程中，出错了：
&nbsp;RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by making sure all `forward` function outputs participate in calculating loss.
我打印了其中的没有梯度的变量，就是module.represent.0.weight
module.represent.1.weight
module.represent.1.bias
module.represent.3.weight
module.represent.3.bias
module.represent.4.weight
module.represent.4.bias
module.represent.6.weight
module.represent.6.bias
没有接收到梯度，我不知道改怎么解决，网上没有好的解决方法，希望您帮帮我，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haochen ***@***.***&gt;; 
发送时间: 2022年6月23日(星期四) 下午4:56
收件人: ***@***.***&gt;; 
抄送: "완 \(ˆoˆ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Haochen-Wang409/U2PL] 正例的计算问题 (Issue #58)





 
您训练的是半监督模型还是全监督的 SupOnly 模型呢？能够提供一下 log 嘛

**Comment by NJNUCS** [comment]
您好，我就是用的您的代码进行对比损失，然后这个对比损失更新不了表征头的梯度，有点迷




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haochen ***@***.***&gt;; 
发送时间: 2022年6月23日(星期四) 下午5:29
收件人: ***@***.***&gt;; 
抄送: "완 \(ˆoˆ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Haochen-Wang409/U2PL] 正例的计算问题 (Issue #58)





 
这是由于您计算的损失没有包括表征头的梯度呀。您可以参考代码：https://github.com/Haochen-Wang409/U2PL/blob/main/train_semi.py#L483 进行 contrastive loss 的计算。
 
或者，如果您不想在早期训练加入 contrastive loss，您可以尝试这样：https://github.com/Haochen-Wang409/U2PL/blob/main/train_semi.py#L307

**Comment by Haochen-Wang409** [comment]
您用的是哪个训练脚本，在哪个数据集上训练，我们的模型内有提供表征头，您为什么需要额外加一个呢

**Comment by NJNUCS** [comment]
训练脚本用的是pytorch, 我用的是resnet50+psp的网络，没有表示头，我需要加一个，

**Comment by NJNUCS** [comment]
加了表示头之后，梯度传不到表示头中，真奇怪

**Comment by NJNUCS** [comment]
您好，如果我想把对比损失的特征表示调到512维度，而不是256维度，我应该调那些地方呀。

**Comment by Haochen-Wang409** [comment]
调整self.representation的最后一层卷积的out_channels
您方便提供您修改后的 pspnet 代码嘛？

**Comment by NJNUCS** [comment]
我的psp输出的维度是512，我想把这个作为特征的表示，送到对比学习中求对比损失，关于memobank、queue_size.queue_ptrlis、que_size、prototype做怎样的调整呀，谢谢您

**Comment by Haochen-Wang409** [comment]
所有涉及到特征维度的 (e.g., 256) 都改成 512 即可
