### ISSUE TITLE
Training with U2PL+Cutmix is normal, but training with U2PL+AEL reports an error

### ISSUE THREAD

**Issue by licongguan** [Haochen-Wang409/U2PL#59]
$ sh train.sh 2 23332

usage: train.py [-h] [--config CONFIG] [--port PORT] [--seed SEED]
train.py: error: unrecognized arguments: --local_rank=1
usage: train.py [-h] [--config CONFIG] [--port PORT] [--seed SEED]
train.py: error: unrecognized arguments: --local_rank=0
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/torch1.8/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dell/anaconda3/envs/torch1.8/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dell/anaconda3/envs/torch1.8/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/dell/anaconda3/envs/torch1.8/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/dell/anaconda3/envs/torch1.8/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dell/anaconda3/envs/torch1.8/bin/python', '-u', '../../train.py', '--local_rank=1', '--config=config.yaml', '--seed', '1', '--port', '23332']' returned non-zero exit status 2.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Killing subprocess 83638
Killing subprocess 83639

**Comment by Haochen-Wang409** [comment]
Did you use the ```train.sh``` in branch ```with_AEL```?

**Comment by licongguan** [comment]
Yes, I am using the AEL branch

**Comment by Haochen-Wang409** [comment]
Sorry for the bug. 
In fact, we trained with AEL by slurm and did not try using ```torch.distributed.launch```.

I guess you could modify ```train.py``` and add an arguments named ```local_rank``` like [here](https://github.com/Haochen-Wang409/U2PL/blob/with_AEL/experiments/city_744/train.sh)

**Comment by Haochen-Wang409** [comment]
We have commited the code, please fetch the latest code and try it again~
