### ISSUE TITLE
这个sh train.sh <num_gpu> <port>中的port是填什么呀...

### ISSUE THREAD

**Issue by MLuminous** [Haochen-Wang409/U2PL#6]
学长这个1个gpu能跑起来吗，这个sh train.sh <num_gpu> <port>中的port是填什么呀...这个port..

**Comment by BIGBALLON** [comment]
num_gpu 代表使用多少gpu，只有一张卡用1  
port 代表分布式训练实验的端口号，建议使用大于10000的端口号，比如23500
