### ISSUE TITLE
U2PL+cutmix

### ISSUE THREAD

**Issue by licongguan** [Haochen-Wang409/U2PL#60]
In the 744 group of the cityscapes dataset, when using U2PL+Cutmix training, the mIoU results of each round fluctuated and were unstable. When training to 200 epochs, using sh eval.sh for evaluation, the mIoU result is 74.76, which does not reach the accuracy of 76.47 in the paper. Has anyone else encountered this situation?

**Comment by Haochen-Wang409** [comment]
I received your provided log from email, and I have replied you.

**Comment by syqisme** [comment]
您好，最近我在您的项目上进行修改，在pascalvoc数据集上效果正常，可是放到cityscapes数据集上效果就很差，目前没找到具体原因，如果可以的话，是否可以提供一下他的问题和解决方式呢？我想借鉴一下，谢谢！
