### ISSUE TITLE
熵的可视化图像如何绘制的

### ISSUE THREAD

**Issue by srzxDragon** [Haochen-Wang409/U2PL#61]
作者你好，首先很感谢你的提出的模型，效果确实不错。我想问的问题是，论文中Figure 2(a)这种图是怎么画的。如果有代码的话就更好了，万分感谢。
![image](https://user-images.githubusercontent.com/87605861/175848555-08e66462-bbda-4f0f-b174-9353beb8b2b5.png)

**Comment by Haochen-Wang409** [comment]
以下是伪代码：
```
pred = model(img)['pred'][0]   # (c, h, w)
prob = softmax(pred, dim=0)
entropy = sum(prob * log(prob + 1e-10), dim=0)
entropy_show = exp(-entropy) * 255
entropy_show = cv2.applyColorMap(entropy_show.astype(np.uint8), cv2.COLORMAP_JET)
img_show = cv2.addWeighted(img, 0.5, entropy_show, 0.5, 0)
```

**Comment by srzxDragon** [comment]
非常感谢您的及时回复！

**Comment by NJNUCS** [comment]
您好，你的数据集预处理之后输出：
image, label = self.transform(image, label)
return image[0], label[0, 0].long()
为什么输出image[0]，而不是image,还有label[0,0]呀，希望能帮我解答，谢谢你呀

**Comment by Haochen-Wang409** [comment]
请问是哪一个代码文件中的哪一行？

**Comment by NJNUCS** [comment]
在文件夹u2pl中的dataset的cityscapes的第41行

**Comment by Haochen-Wang409** [comment]
因为我们的 transform 的 ToTensor 操作会扩展图片的维度：
https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/dataset/augmentation.py#L51

**Comment by Haochen-Wang409** [comment]
针对 image: https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/dataset/augmentation.py#L80
针对 label: https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/dataset/augmentation.py#L80

**Comment by NJNUCS** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haochen ***@***.***&gt;; 
发送时间: 2022年7月2日(星期六) 晚上6:48
收件人: ***@***.***&gt;; 
抄送: "완 \(ˆoˆ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Haochen-Wang409/U2PL] 熵的可视化图像如何绘制的 (Issue #61)





 
针对 image: https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/dataset/augmentation.py#L80
 针对 label: https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/dataset/augmentation.py#L83

**Comment by YUCOCOCS** [comment]
我按照您的方法做了熵的可视化的图，应该是蓝色的区域是熵比较低的区域，红色的区域是熵比较高的区域吧

![2007_004649_entropy](https://github.com/Haochen-Wang409/U2PL/assets/127319575/5b6186ee-de8c-4b5c-b269-84c0890e7d6e)

**Comment by Haochen-Wang409** [comment]
是的，红色为高熵区域，蓝色为低熵区域

**Comment by Fly-Yun-Maker** [comment]
谢谢您的回答
&nbsp;


?&nbsp;\(?o?&nbsp;)/
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haochen ***@***.***&gt;; 
发送时间: 2023年5月13日(星期六) 中午11:49
收件人: ***@***.***&gt;; 
抄送: "완 \(ˆoˆ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Haochen-Wang409/U2PL] 熵的可视化图像如何绘制的 (Issue #61)





 
是的，红色为高熵区域，蓝色为低熵区域
