### ISSUE TITLE
集群训练报错

### ISSUE THREAD

**Issue by Yan1026** [Haochen-Wang409/U2PL#62]
您好，我在使用集群训练时发生了错误。我申请了2*GPU，训练时使用语句： sh train.sh 2 21350    报错如下：

             'optimizer': {'kwargs': {'lr': 0.0005,
                                      'momentum': 0.9,
                                      'weight_decay': 0.0001},
                           'type': 'SGD'},
             'unsupervised': {'TTA': False,
                              'apply_aug': 'cutmix',
                              'drop_percent': 80}}}
set random seed to 2
Traceback (most recent call last):
  File "/home/----/.conda/envs/u2pl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/---/.conda/envs/u2pl/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/---/.conda/envs/u2pl/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/---/.conda/envs/u2pl/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home---/.conda/envs/u2pl/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/---/.conda/envs/u2pl/bin/python', '-u', '../../../../train_semi.py', '--local_rank=1', '--config=config.yaml', '--seed', '2', '--port', '21350']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Killing subprocess 191625
Killing subprocess 191626

我又使用语句  sh slurm_train.sh 2 22258  cnGPUtest   ，log文件一开始无内容，过一会儿显示：
srun: Job 112425 step creation temporarily disabled, retrying (Requested nodes are busy)

使用两个语句期间GPU均空闲

请问是我哪里没有设置对吗？希望能得到您的解答

**Comment by Yan1026** [comment]
我跑的是VOC1464，半监督模型

**Comment by Haochen-Wang409** [comment]
您是在本地进行训练还是在拥有 slurm 调度模式的集群进行训练？即，您的 GPU 是在本地的嘛？

**Comment by BIGBALLON** [comment]
可以贴一下你完整的报错信息，环境配置，以及你的运行命令吗

**Comment by Yan1026** [comment]
您好，我不是在本地进行训练的。可能是这个原因或者是分布式训练的原因吗？之前我在本地单卡可以顺利训练。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haochen-Wang409/U2PL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月29日(星期三) 晚上10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haochen-Wang409/U2PL] 集群训练报错 (Issue #62)





 
您是在本地进行训练还是在拥有 slurm 调度模式的集群进行训练？即，您的 GPU 是在本地的嘛？

**Comment by Yan1026** [comment]
好的
1.报错信息：
Traceback (most recent call last):
&nbsp; File "../../../../train_semi.py", line 658, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "../../../../train_semi.py", line 62, in main
&nbsp; &nbsp; rank, word_size = setup_distributed(port=args.port)
&nbsp; File "/home/ user/djy/U2PL/u2pl/utils/dist_helper.py", line 44, in setup_distributed
&nbsp; &nbsp; rank=rank,
&nbsp; File "/home/ user/.conda/envs/u2pl/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 500, in init_process_group
&nbsp; &nbsp; store, rank, world_size = next(rendezvous_iterator)
&nbsp; File "/home/ user/.conda/envs/u2pl/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 190, in _env_rendezvous_handler
&nbsp; &nbsp; store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
[2022-06-29 00:42:04,399][&nbsp; &nbsp; INFO] {'criterion': {'kwargs': {'use_weight': False}, 'type': 'CELoss'},
&nbsp;'dataset': {'batch_size': 8,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'ignore_label': 255,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'mean': [123.675, 116.28, 103.53],
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'n_sup': 1464,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'noise_std': 0.1,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'std': [58.395, 57.12, 57.375],
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'train': {'GaussianBlur': False,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'crop': {'size': [513, 513], 'type': 'rand'},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'data_list': '../../../../data/splits/pascal/1464/labeled.txt',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'data_root': '../../../../data/VOC2012',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'flip': True,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'rand_resize': [0.5, 2.0]},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'type': 'pascal_semi',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'val': {'crop': {'size': [513, 513], 'type': 'center'},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'data_list': '../../../../data/splits/pascal/val.txt',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'data_root': '../../../../data/VOC2012'},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'workers': 2},
&nbsp;'exp_path': '',
&nbsp;'net': {'decoder': {'kwargs': {'dilations': [12, 24, 36], 'inner_planes': 256},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'type': 'u2pl.models.decoder.dec_deeplabv3_plus'},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'ema_decay': 0.99,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'encoder': {'kwargs': {'fpn': True,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'multi_grid': True,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'replace_stride_with_dilation': [False,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;True,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;True],
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'zero_init_residual': True},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'type': 'u2pl.models.resnet.resnet101'},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'num_classes': 21,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'sync_bn': True},
&nbsp;'save_path': 'checkpoints',
&nbsp;'saver': {'pretrain': '', 'snapshot_dir': 'checkpoints'},
&nbsp;'trainer': {'contrastive': {'current_class_negative_threshold': 1,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'current_class_threshold': 0.3,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'high_rank': 20,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'low_entropy_threshold': 20,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'low_rank': 3,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'negative_high_entropy': True,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'num_negatives': 50,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'num_queries': 256,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'temperature': 0.5,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'unsupervised_entropy_ignore': 80},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'epochs': 80,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'eval_on': True,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'lr_scheduler': {'kwargs': {'power': 0.9}, 'mode': 'poly'},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'optimizer': {'kwargs': {'lr': 0.0005,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'momentum': 0.9,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'weight_decay': 0.0001},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'type': 'SGD'},
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;'unsupervised': {'TTA': False,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'apply_aug': 'cutmix',
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 'drop_percent': 80}}}
set random seed to 2
Traceback (most recent call last):
&nbsp; File "/home/ user/.conda/envs/u2pl/lib/python3.6/runpy.py", line 193, in _run_module_as_main
&nbsp; &nbsp; "__main__", mod_spec)
&nbsp; File "/home/ user/.conda/envs/u2pl/lib/python3.6/runpy.py", line 85, in _run_code
&nbsp; &nbsp; exec(code, run_globals)
&nbsp; File "/home/ user/.conda/envs/u2pl/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module&gt;
&nbsp; &nbsp; main()
&nbsp; File "/home/ user/.conda/envs/u2pl/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
&nbsp; &nbsp; sigkill_handler(signal.SIGTERM, None)&nbsp; # not coming back
&nbsp; File "/home/ user/.conda/envs/u2pl/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
&nbsp; &nbsp; raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ user/.conda/envs/u2pl/bin/python', '-u', '../../../../train_semi.py', '--local_rank=1', '--config=config.yaml', '--seed', '2', '--port', '21350']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.&nbsp;
*****************************************
Killing subprocess 191625
Killing subprocess 191626



端口号我也换了，不知为何还有Address already in use的报错


2.环境配置
与作者在主页上的配置一致
cuda 11.3（是这个原因吗？）
2*V100(16G)


3.运行命令
nohup sh train.sh 2 21350&nbsp; &amp;


另运行 “nohup sh slurm_train.sh 2 22258&nbsp; cnGPUtest&nbsp; &amp;” 时报错：Killing subprocess 191625




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WILL ***@***.***&gt;; 
发送时间: 2022年6月30日(星期四) 凌晨4:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Haochen-Wang409/U2PL] 集群训练报错 (Issue #62)





 
可以贴一下你完整的报错信息，环境配置，以及你的运行命令吗

**Comment by BIGBALLON** [comment]
1. ``RuntimeError: Address already in use`` 这个错误确实是端口被占用了，试试看有没有僵尸进程存在？或者用一个比较冷门的port，如23302,41890等
2. 最裸的多卡程序你是否能正常运行呢？
3. slurm的使用是否正确呢？

**Comment by Yan1026** [comment]
感谢您的解答！
关于2.同门的多卡训练可以正常进行
关于3. 想请问一下，我应该使用slurm_train.sh进行训练还是使用train.sh进行训练呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WILL ***@***.***&gt;; 
发送时间: 2022年6月30日(星期四) 中午11:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Haochen-Wang409/U2PL] 集群训练报错 (Issue #62)





  
RuntimeError: Address already in use 这个错误确实是端口被占用了，试试看有没有僵尸进程存在？或者用一个比较冷门的port，如23302,41890等
 
最裸的多卡程序你是否能正常运行呢？
 
slurm的使用是否正确呢？

**Comment by BIGBALLON** [comment]
1. 先不管同门，你先自己尝试是否能把分布式(数据并行)的程序跑起来
2. 跑之前最好先理顺一下DDP的使用逻辑(进程组初始化，进程间通讯，launch 和 slurm调度的细节区别)
3. 这里在集群上如果是多机，肯定是用slrum方便一些，如果是单机，可以用launch的方式，slurm只是用于提交任务，并不做多进程的初始化，初始化交给launch去做，也可以用slrum直接进行多进程调度，所以这个不是用slrum_train 还是 train的问题，是你实际的集群想怎么使用的问题，建议参考[distribuuuu](https://github.com/BIGBALLON/distribuuuu) [doc](https://zhuanlan.zhihu.com/p/360405558)

**Comment by Yan1026** [comment]
受教了，感谢您的回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "WILL ***@***.***&gt;; 
发送时间: 2022年6月30日(星期四) 中午11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Haochen-Wang409/U2PL] 集群训练报错 (Issue #62)





  
先不管同门，你先自己尝试是否能把分布式(数据并行)的程序跑起来
 
跑之前最好先理顺一下DDP的使用逻辑(进程组初始化，进程间通讯，launch 和 slurm调度的细节区别)
 
这里在集群上如果是多机，肯定是用slrum方便一些，如果是单机，可以用launch的方式，slurm只是用于提交任务，并不做多进程的初始化，初始化交给launch去做，也可以用slrum直接进行多进程调度，所以这个不是用slrum_train 还是 train的问题，是你实际的集群想怎么使用的问题，建议参考distribuuuu doc
