### ISSUE TITLE
关于网络模型

### ISSUE THREAD

**Issue by zhangh0920** [Haochen-Wang409/U2PL#65]
看完论文有几个问题想请问一下，在您的论文中分学生网络和教师网络的用处是什么呢？教师网络利用EMA更新而不是利用loss更新参数的目的是什么呢？

**Comment by Haochen-Wang409** [comment]
老师模型用于对无标签数据产生伪标签。试想一下，如果没有老师模型，对于无标签数据应该如何利用呢？如果让模型自己产生伪标签，那 loss 将一直保持为 0 的状态了

此外，EMA 相当于一种时序上的模型集成，一般来说效果会更好

**Comment by zhangh0920** [comment]
我看论文中没有提到老师网络先使用有标签的数据训练过，那老师网络和学生网络都是随机初始化的吗？如果都是随机初始化的话，那这个老师模型产生的伪标签和学生模型产生的伪标签不就是几乎一致的吗

**Comment by Haochen-Wang409** [comment]
是的，正因为如此，我们设置了“冷启动”的 epoch，即在训练前期只采用 loss_sup
对于 VOC 数据集，sup_only_epoch =  1，而 cityscapes 则为 20

**Comment by zhangh0920** [comment]
非常感谢您的解答！
