### ISSUE TITLE
eval中name_path中的 .mat文件内部什么格式？

### ISSUE THREAD

**Issue by Linuxer888** [Haochen-Wang409/U2PL#68]
eval中name_path中的 .mat文件内部什么格式？

**Comment by munanning** [comment]
什么代码都不用改，去下载作者的新label就好了

**Comment by Haochen-Wang409** [comment]
您可以尝试下载新提供的 label 文件 @Linuxer888

**Comment by Linuxer888** [comment]
打算使用自己的数据集训练下。。。

**Comment by Haochen-Wang409** [comment]
您指的是 ```args.names_path``` 这个参数嘛：https://github.com/Haochen-Wang409/U2PL/blob/main/eval.py#L50
实际上，```eval.py``` 中没有用到 ```args.names_path``` 这个参数，因此应该不需要做其他修改

**Comment by Linuxer888** [comment]
您好，我目前是在训练的时候，miou还能到79点多，就是在测试的时候，除了背景外，其余都是0。。这个我只训练了60epoch，设备有限

**Comment by Haochen-Wang409** [comment]
您指的是训练过程中每个 epoch 的测试结果 mIoU 可以到 79，而在 ```eval.py``` 中，mIoU 就降到 0 了是吗？
您是否可以提供训练和测试的 log？

**Comment by Linuxer888** [comment]
可以

**Comment by Linuxer888** [comment]
新手一个，谢谢您了

**Comment by Linuxer888** [comment]
> 您指的是训练过程中每个 epoch 的测试结果 mIoU 可以到 79，而在 `eval.py` 中，mIoU 就降到 0 了是吗？ 您是否可以提供训练和测试的 log？

什么方式给您发呢？

**Comment by Haochen-Wang409** [comment]
github issue 就可以传文件，直接拖拽进来即可

**Comment by Linuxer888** [comment]
[log.tar.gz](https://github.com/Haochen-Wang409/U2PL/files/9125314/log.tar.gz)

**Comment by Linuxer888** [comment]
> github issue 就可以传文件，直接拖拽进来即可
[log.tar.gz](https://github.com/Haochen-Wang409/U2PL/files/9125330/log.tar.gz)

**Comment by Haochen-Wang409** [comment]
你提供的文件中有很多 log，哪些能反映你当前的问题？

**Comment by Richardcvpr** [comment]
您好，我在跑train_sup.py的时候发现报错  raise KeyError(key) from None  KeyError: 'RANK'，好像是port的参数没有设置好，请问这个参数是什么意思呢？还有需要设置的local-rank，以及seed，分别代表什么呢？

**Comment by Haochen-Wang409** [comment]
是否使用了 torch.distributed.launch?
