### ISSUE TITLE
sh train.sh 1 23500 encounter a mistake

### ISSUE THREAD

**Issue by MLuminous** [Haochen-Wang409/U2PL#7]
sh train.sh 1 23500 encounter a mistake ，I don't know where I am going wrong, can you help me
![123](https://user-images.githubusercontent.com/32741409/158112532-46b5ca49-9e78-4e1e-9620-3f8c8360197f.jpg)

**Comment by Haochen-Wang409** [comment]
Sorry, I uploaded the wrong config. Please fetch the latest code.

If you have any problems after doing this, do not hesitate to contact me.

By the way, you are suggested to use 2 GPUs for reproducing ```SupOnly``` results for VOC.
