### ISSUE TITLE
Train custom data

### ISSUE THREAD

**Issue by Holmes2002** [Haochen-Wang409/U2PL#74]
Can you explain how to train custom data please ?

**Comment by Haochen-Wang409** [comment]
Just modify data-specific parameters (e.g., ```data_root```, ```data_list``` ```num_classes```) in ```config.yaml```.

**Comment by Holmes2002** [comment]
Should I adjust parameter  num_negatives in config file for custom data ?

**Comment by LuizZillmann** [comment]
Also, how to generate custom SegmentationClassAug for custom data? Any tips on this?

**Comment by Haochen-Wang409** [comment]
> 

The ```num_negatives``` means the number of negative keys per query in contrastive learning. Our method is robust against this parameter. Thus, I don't think it worth tuning for custom data.
However, if you fail to get expected results, it can be ablated on your dataset.

**Comment by Haochen-Wang409** [comment]
> Should I adjust parameter num_negatives in config file for custom data ?

The `num_negatives` means the number of negative keys per query in contrastive learning. Our method is robust against this parameter. Thus, I don't think it worth tuning for custom data. However, if you fail to get expected results, it can be ablated on your dataset.

**Comment by Haochen-Wang409** [comment]
> Also, how to generate SegmentationClassAug for custom data? Any tips on this?

```SegmentationClassAug``` is the ground-truths for each input images.
Assume we have an image with shape ```HxWx3```, thus the corresponding ground-truth should be ```HxW```.
And each emelent denotes the class for each pixel.
