### ISSUE TITLE
训练过程

### ISSUE THREAD

**Issue by DeeplearningXiaobai** [Haochen-Wang409/U2PL#75]
您好，请问您能将VOC2012的1/8训练过程中生成的.txt文件给我看一下吗？

**Comment by Haochen-Wang409** [comment]
是 blender VOC 还是 classic VOC?

**Comment by DeeplearningXiaobai** [comment]
您好，是blender PASCAL VOC 2012（79.01）的训练生成的.txt文件

**Comment by Haochen-Wang409** [comment]
我们没有保留 79.01 的 log 文件，但有一个 resume 后 79.13 的 log 文件，供您参参考：[log.txt](https://github.com/Haochen-Wang409/U2PL/files/9299133/log.txt)

**Comment by DeeplearningXiaobai** [comment]
好的，谢谢您的分享
