### ISSUE TITLE
关于Tabel1中的实验部分

### ISSUE THREAD

**Issue by FrankYii1** [Haochen-Wang409/U2PL#77]
作者您好，又来叨扰了，首先感谢作者发布的优秀论文。                                                                                                                              想请问一下您：
1. 在Table 1最后一列的Full栏中，U2PL的实验是怎么设计的？是否是将1464张图片全部作为标记图片，并且不使用无标记图像吗？   
2. 在Full的条件下，U2PL的模型相对于Suponly的原始模型有什么区别？为什么MIOU提升会这么大？

**Comment by Haochen-Wang409** [comment]
Full 的意思是，使用 1464 张高质量标注图片作为有标签图像，剩余 9118 低质量标注的图片作为无标签图像。因此，此时的 SupOnly 表示只使用 1464 张有标签图像训练，而半监督方法会额外使用剩余的 9118 张图像

Table 1 的不同数字，表示的是有标签图像数量占高质量标注图像的比例。例如，1/2 就表示从 1464 张图片中随机选取 732 张作为有标签图像，剩余的 732 张 + 9118 张 作为无标签图像
