### ISSUE TITLE
单卡运行train.sh文件遇见了很大的问题

### ISSUE THREAD

**Issue by yang654123** [Haochen-Wang409/U2PL#79]
![image](https://user-images.githubusercontent.com/64208861/187057628-5f1d2e7d-98aa-4bb5-9d50-d7ac5c5af460.png)
![image](https://user-images.githubusercontent.com/64208861/187057645-2b29d0be-7a33-459e-98f9-1d67a196eda9.png)
如图，这个问题，希望作者可以给出单卡的运行解决方案，感谢您百忙之中的回复

**Comment by Haochen-Wang409** [comment]
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/62472073/187057735-d7124eb3-9b35-4d75-a5ff-895cef79f212.png">
看您的报错，应该是数据集的问题，您可以参照 README 中的方法准备数据集

**Comment by yang654123** [comment]
> <img alt="image" width="1064" src="https://user-images.githubusercontent.com/62472073/187057735-d7124eb3-9b35-4d75-a5ff-895cef79f212.png">
> 
> 看您的报错，应该是数据集的问题，您可以参照 README 中的方法准备数据集

你好，我使用的经典的pascal，splits用的st++论文的，这样也会出现问题么

**Comment by Haochen-Wang409** [comment]
您的数据集没有存放在 ```../../../../data/VOC2012``` 这个目录下吧？您可以修改 ```config.yaml``` 中的 ```data_root```

**Comment by yang654123** [comment]
> 您的数据集没有存放在 `../../../../data/VOC2012` 这个目录下吧？您可以修改 `config.yaml` 中的 `data_root`

自己创了一个文件存放pretrain    和 pascal 数据集 和  splits    放在了U2PL文件下级目录里

**Comment by Haochen-Wang409** [comment]
您可以展示一下您当前 ```U2PL``` 文件夹下的目录结构吗

**Comment by yang654123** [comment]
> 您可以展示一下您当前 `U2PL` 文件夹下的目录结构吗

![image](https://user-images.githubusercontent.com/64208861/187058310-f287a54f-3615-4417-a17d-a8ea2ec849e1.png)

**Comment by Haochen-Wang409** [comment]
您当前的 VOC 的数据 (指的是图片以及对应的分割标签) 没有存放在 ```U2PL/data``` 目录下，所以需要更改 ```config.yaml``` 中的 ```data_root```

**Comment by yang654123** [comment]
├── data
│   └── splits
│       ├── cityscapes
│       │   ├── 1488
│       │   │   ├── labeled.txt
│       │   │   └── unlabeled.txt
│       │   ├── 186
│       │   │   ├── labeled.txt
│       │   │   └── unlabeled.txt
│       │   ├── 372
│       │   │   ├── labeled.txt
│       │   │   └── unlabeled.txt
│       │   ├── 744
│       │   │   ├── labeled.txt
│       │   │   └── unlabeled.txt
│       │   └── val.txt
│       └── pascal
│           ├── 1323
│           │   ├── labeled.txt
│           │   └── unlabeled.txt
│           ├── 1464
│           │   ├── labeled.txt
│           │   └── unlabeled.txt
│           ├── 183
│           │   ├── labeled.txt
│           │   └── unlabeled.txt
│           ├── 2646
│           │   ├── labeled.txt
│           │   └── unlabeled.txt
│           ├── 366
│           │   ├── labeled.txt
│           │   └── unlabeled.txt
│           ├── 5291
│           │   ├── labeled.txt
│           │   └── unlabeled.txt
│           ├── 662
│           │   ├── labeled.txt
│           │   └── unlabeled.txt
│           ├── 732
│           │   ├── labeled.txt
│           │   └── unlabeled.txt
│           ├── 92
│           │   ├── labeled.txt
│           │   └── unlabeled.txt
│           └── val.txt
├── dataset
│   └── VOCdevkit
│       ├── splits
│       │   ├── cityscapes
│       │   │   ├── 1_30
│       │   │   │   ├── split_0
│       │   │   │   │   ├── labeled.txt
│       │   │   │   │   └── unlabeled.txt
│       │   │   │   ├── split_1
│       │   │   │   │   ├── labeled.txt
│       │   │   │   │   └── unlabeled.txt
│       │   │   │   └── split_2
│       │   │   │       ├── labeled.txt
│       │   │   │       └── unlabeled.txt
│       │   │   ├── 1_4
│       │   │   │   ├── split_0
│       │   │   │   │   ├── labeled.txt
│       │   │   │   │   └── unlabeled.txt
│       │   │   │   ├── split_1
│       │   │   │   │   ├── labeled.txt
│       │   │   │   │   └── unlabeled.txt
│       │   │   │   └── split_2
│       │   │   │       ├── labeled.txt
│       │   │   │       └── unlabeled.txt
│       │   │   ├── 1_8
│       │   │   │   ├── split_0
│       │   │   │   │   ├── labeled.txt
│       │   │   │   │   └── unlabeled.txt
│       │   │   │   ├── split_1
│       │   │   │   │   ├── labeled.txt
│       │   │   │   │   └── unlabeled.txt
│       │   │   │   └── split_2
│       │   │   │       ├── labeled.txt
│       │   │   │       └── unlabeled.txt
│       │   │   └── val.txt
│       │   └── pascal
│       │       ├── 1_16
│       │       │   ├── split_0
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   ├── split_1
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   └── split_2
│       │       │       ├── labeled.txt
│       │       │       └── unlabeled.txt
│       │       ├── 1_4
│       │       │   ├── split_0
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   ├── split_1
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   └── split_2
│       │       │       ├── labeled.txt
│       │       │       └── unlabeled.txt
│       │       ├── 1.4k
│       │       │   ├── labeled.txt
│       │       │   └── unlabeled.txt
│       │       ├── 1_8
│       │       │   ├── split_0
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   ├── split_1
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   └── split_2
│       │       │       ├── labeled.txt
│       │       │       └── unlabeled.txt
│       │       ├── 183
│       │       │   ├── split_0
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   ├── split_1
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   └── split_2
│       │       │       ├── labeled.txt
│       │       │       └── unlabeled.txt
│       │       ├── 366
│       │       │   ├── split_0
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   ├── split_1
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   └── split_2
│       │       │       ├── labeled.txt
│       │       │       └── unlabeled.txt
│       │       ├── 732
│       │       │   ├── split_0
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   ├── split_1
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   └── split_2
│       │       │       ├── labeled.txt
│       │       │       └── unlabeled.txt
│       │       ├── 92
│       │       │   ├── split_0
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   ├── split_1
│       │       │   │   ├── labeled.txt
│       │       │   │   └── unlabeled.txt
│       │       │   └── split_2
│       │       │       ├── labeled.txt
│       │       │       └── unlabeled.txt
│       │       └── val.txt
│       └── VOC2012
^C

**Comment by Haochen-Wang409** [comment]
或者把 ```dataset/VOCdevkit/VOC2012``` 下的文件都复制到 ```data/VOC2012``` 下

**Comment by yang654123** [comment]
> 或者把 `dataset/VOCdevkit/VOC2012` 下的文件都复制到 `data/VOC2012` 下

好嘞

**Comment by yang654123** [comment]
> 或者把 `dataset/VOCdevkit/VOC2012` 下的文件都复制到 `data/VOC2012` 下

对了，应该不好使，因为config中的split文件路径不同 我用的st的split

**Comment by Haochen-Wang409** [comment]
修改 ```config.yaml``` 中的 ```data_root``` 和 ```data_list``` 就可以了
https://github.com/Haochen-Wang409/U2PL/blob/main/experiments/pascal/1464/ours/config.yaml#L4-L5

**Comment by yang654123** [comment]
> 修改 `config.yaml` 中的 `data_root` 和 `data_list` 就可以了 https://github.com/Haochen-Wang409/U2PL/blob/main/experiments/pascal/1464/ours/config.yaml#L4-L5

好嘞，十分感谢

**Comment by yang654123** [comment]
> 修改 `config.yaml` 中的 `data_root` 和 `data_list` 就可以了 https://github.com/Haochen-Wang409/U2PL/blob/main/experiments/pascal/1464/ours/config.yaml#L4-L5
我更改之后 ![image](https://user-images.githubusercontent.com/64208861/187059329-79aeb62c-c057-4c89-8271-4f3a5cd024e0.png)
发生了这个问题
![image](https://user-images.githubusercontent.com/64208861/187059310-1b52b3f5-319d-448a-8dfd-a5542e81ed6e.png)

**Comment by Haochen-Wang409** [comment]
可能是split的内容不一致，请您仔细对照两个split的具体内容后，对 ```u2pl/dataset/base.py``` 进行针对性修改
https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/dataset/base.py#L12-L41

**Comment by Haochen-Wang409** [comment]
您也可以选择参考 ST++ 的代码进行修改

**Comment by yang654123** [comment]
> 可能是split的内容不一致，请您仔细对照两个split的具体内容后，对 `u2pl/dataset/base.py` 进行针对性修改 https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/dataset/base.py#L1
好的我试试

**Comment by yang654123** [comment]
作者您好，我想问一下，如果想加checkpoint 应该在在哪里添加。谢谢您

**Comment by Haochen-Wang409** [comment]
如果您是想 load pretrain model (比如训练完了一个 1/16 的模型，想在训练 1/4 模型时先 load pretrain)，可以在这里加：
https://github.com/Haochen-Wang409/U2PL/blob/main/experiments/pascal/1464/ours/config.yaml#L58

如果是想 load pretrained backbone，可以在 ```u2pl/models/resnet.py``` 中的 ```model_urls``` 里面修改

**Comment by yang654123** [comment]
> 如果您是想 load pretrain model (比如训练完了一个 1/16 的模型，想在训练 1/4 模型时先 load pretrain)，可以在这里加： https://github.com/Haochen-Wang409/U2PL/blob/main/experiments/pascal/1464/ours/config.yaml#L58
> 
> 如果是想 load pretrained backbone，可以在 `u2pl/models/resnet.py` 中的 `model_urls` 里面修改

就是怕出现服务器不稳的情况导致代码跑到一半，突然断了，得重新跑，所以想加个checkpoint保存目前模型最优的训练参数

**Comment by Haochen-Wang409** [comment]
在 config.yaml 的 saver 字段中加入 ```auto_resume: True```
