### ISSUE TITLE
Questions about VOC dataset 

### ISSUE THREAD

**Issue by HeimingX** [Haochen-Wang409/U2PL#8]
Hi, thanks for the code sharing and I plan to run some basic experiments based on the tutorial in README file. I use the link [http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar] to download the VOC dataset, but I just found that it does not contain the SegmentationClassAug folder which is required in your code [https://github.com/Haochen-Wang409/U2PL/blob/97284dbbddce4a65d00621bfe77863f39db9ddcd/u2pl/dataset/base.py#L27]. Could you please have a double check? Thanks

**Comment by Haochen-Wang409** [comment]
Hi, it might because the GT labels of each images are ```RGB``` rather than ```GRAY```.
You can map the ```color``` value for each RGB pixel to ```id```.
```python
labels = [
    #           class name            id    trainId         color
    Label(  'background'            ,  0 ,        0 , (   0,   0,   0) ),
    Label(  'aeroplane'             ,  1 ,        1 , ( 128,   0,   0) ),
    Label(  'bicycle'               ,  2 ,        2 , (   0, 128,   0) ),
    Label(  'bird'                  ,  3 ,        3 , ( 128, 128,   0) ),
    Label(  'boat'                  ,  4 ,        4 , (   0,   0, 128) ),
    Label(  'bottle'                ,  5 ,        5 , ( 128,   0, 128) ),
    Label(  'bus'                   ,  6 ,        6 , (   0, 128, 128) ),
    Label(  'car'                   ,  7 ,        7 , ( 128, 128, 128) ),
    Label(  'cat'                   ,  8 ,        8 , (  64,   0,   0) ),
    Label(  'chair'                 ,  9 ,        9 , ( 192,   0,   0) ),
    Label(  'cow'                   , 10 ,       10 , (  64, 128,   0) ),
    Label(  'dining table'          , 11 ,       11 , ( 192, 128,   0) ),
    Label(  'dog'                   , 12 ,       12 , (  64,   0, 128) ),
    Label(  'horse'                 , 13 ,       13 , ( 192,   0, 128) ),
    Label(  'motorbike'             , 14 ,       14 , (  64, 128, 128) ),
    Label(  'person'                , 15 ,       15 , ( 192, 128, 128) ),
    Label(  'potted plant'          , 16 ,       16 , (   0,  64,   0) ),
    Label(  'sheep'                 , 17 ,       17 , ( 128,  64,   0) ),
    Label(  'sofa'                  , 18 ,       18 , (   0, 192,   0) ),
    Label(  'train'                 , 19 ,       19 , ( 128, 192,   0) ),
    Label(  'tv monitor'            , 20 ,       20 , (   0,  64, 128) ),
    Label(  'bordering region'      , 255,       21 , ( 224, 224, 192) ),
]
```

**Comment by HeimingX** [comment]
> Hi, it might because the GT labels of each images are `RGB` rather than `GRAY`. You can map the `color` value for each RGB pixel to `id`.
> 
> ```python
> labels = [
>     #           class name            id    trainId         color
>     Label(  'background'            ,  0 ,        0 , (   0,   0,   0) ),
>     Label(  'aeroplane'             ,  1 ,        1 , ( 128,   0,   0) ),
>     Label(  'bicycle'               ,  2 ,        2 , (   0, 128,   0) ),
>     Label(  'bird'                  ,  3 ,        3 , ( 128, 128,   0) ),
>     Label(  'boat'                  ,  4 ,        4 , (   0,   0, 128) ),
>     Label(  'bottle'                ,  5 ,        5 , ( 128,   0, 128) ),
>     Label(  'bus'                   ,  6 ,        6 , (   0, 128, 128) ),
>     Label(  'car'                   ,  7 ,        7 , ( 128, 128, 128) ),
>     Label(  'cat'                   ,  8 ,        8 , (  64,   0,   0) ),
>     Label(  'chair'                 ,  9 ,        9 , ( 192,   0,   0) ),
>     Label(  'cow'                   , 10 ,       10 , (  64, 128,   0) ),
>     Label(  'dining table'          , 11 ,       11 , ( 192, 128,   0) ),
>     Label(  'dog'                   , 12 ,       12 , (  64,   0, 128) ),
>     Label(  'horse'                 , 13 ,       13 , ( 192,   0, 128) ),
>     Label(  'motorbike'             , 14 ,       14 , (  64, 128, 128) ),
>     Label(  'person'                , 15 ,       15 , ( 192, 128, 128) ),
>     Label(  'potted plant'          , 16 ,       16 , (   0,  64,   0) ),
>     Label(  'sheep'                 , 17 ,       17 , ( 128,  64,   0) ),
>     Label(  'sofa'                  , 18 ,       18 , (   0, 192,   0) ),
>     Label(  'train'                 , 19 ,       19 , ( 128, 192,   0) ),
>     Label(  'tv monitor'            , 20 ,       20 , (   0,  64, 128) ),
>     Label(  'bordering region'      , 255,       21 , ( 224, 224, 192) ),
> ]
> ```

Hi, thanks for the prompt response. But the answer makes me confuse. My question is that the dataset VOC is missing the necessary folder "SegmentationClassAug " which should be the ground truth of augmented VOC2012?

**Comment by Haochen-Wang409** [comment]
Do you mean the ```SBD``` or ```AUG``` VOC?

**Comment by Haochen-Wang409** [comment]
You can download ```SBD``` dataset here: http://home.bharathh.info/pubs/codes/SBD/download.html

**Comment by HeimingX** [comment]
Thanks for the advice, I will have a try~

**Comment by HeimingX** [comment]
Hi, I have downloaded the dataset through the [link](http://www.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/semantic_contours/benchmark.tgz)  based on your suggested [website](http://home.bharathh.info/pubs/codes/SBD/download.html). 

The organization of the downloaded dataset is as follows

```angular2html
benchmark_RELEASE
├── benchmark_code_RELEASE
│   └── source codes....
├── dataset
│   ├── cls  --> 11355 files
│   ├── img --> 11355 files
│   ├── inst --> 11355 files
│   ├── train.txt
│   └── val.txt
├── BharathICCV2011.pdf
└── README
```

Given the downloaded dataset, I still do not known how to obtain the ground truth which is requried in your [code](https://github.com/Haochen-Wang409/U2PL/blob/97284dbbddce4a65d00621bfe77863f39db9ddcd/u2pl/dataset/base.py#L27) (i.e., the files in "SegmentationClassAug" folder should contain augmented VOC2012 ground truth data).

Could you please directly release the "SegmentationClassAug" folder for better experimenting on the released codebase? Many thanks.

**Comment by Haochen-Wang409** [comment]
Could you please provide the organization after unzup files from: http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar?

It been a long time from where I prepared VOC dataset...

**Comment by HeimingX** [comment]
> Could you please provide the organization after unzup files from: http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar?
> 
> It been a long time from where I prepared VOC dataset...

Hi, the organization of VOCtrainval_11-May-2012.tar is as follows:

```angular2html
data/VOC2012
├── Annotations --> 17125 files
├── ImageSets
├── JPEGImages --> 17125 files
├── SegmentationClass --> 2913 files
└── SegmentationObject --> 2913 files
```

**Comment by HeimingX** [comment]
> Maybe you could convert all `png` labels from `ColorMasks` folder with the map function above and save new labels to `SegmentationClassAug`.

Hi, where can i find the `ColorMasks` folder?

**Comment by Haochen-Wang409** [comment]
I see. I think this link (https://github.com/zhixuanli/segmentation-paper-reading-notes/blob/master/others/Summary%20of%20the%20semantic%20segmentation%20datasets.md) will help you.

**Comment by HeimingX** [comment]
> I see. I think this link (https://github.com/zhixuanli/segmentation-paper-reading-notes/blob/master/others/Summary%20of%20the%20semantic%20segmentation%20datasets.md) will help you.

Great！ Thanks a lot~
