### ISSUE TITLE
显存溢出问题

### ISSUE THREAD

**Issue by yang654123** [Haochen-Wang409/U2PL#81]
<img width="985" alt="image" src="https://user-images.githubusercontent.com/64208861/187576955-4c3b193c-d4e2-4b70-92db-0e0bdfeaf70f.png">

你好，作者，我使用8张V100。16G 。保留您的参数不变，结果还是出现了爆显存的问题，请问，这种情况如何应对呢

**Comment by yang654123** [comment]
我调低了batch size为2 可以运行了，但是应该跑不出您的效果了

**Comment by Haochen-Wang409** [comment]
同步调整 learning rate 即可。请仔细阅读 readme 中 note 的部分

**Comment by yang654123** [comment]
> 同步调整 learning rate 即可。请仔细阅读 readme 中 note 的部分

请问同步调整是调整为为多少合适呢，您可否推荐一个，十分感谢，我的batchsize=2

**Comment by Haochen-Wang409** [comment]
几张卡？跑的是VOC还是CS？是SupOnly还是Semi？

**Comment by yang654123** [comment]
> 几张卡？跑的是VOC还是CS？是SupOnly还是Semi？

8张V100 VOC semi

**Comment by Haochen-Wang409** [comment]
降低学习率为原来的一半即可

**Comment by yang654123** [comment]
> 不需要调整学习率，直接训练即可。
> 
> 我们的 config 是 4x4 的 batch_size，你采用的是 2x8，总的都是 16

好的 感谢
