### ISSUE TITLE
Contrastive loss

### ISSUE THREAD

**Issue by Yussef93** [Haochen-Wang409/U2PL#82]
Hi, I've asked previously about it but I'd like to ask again. Regarding eq. 10 selecting the anchor pixels, how is it performed ? what I understood is that you down sample the ground truth to the size of the representation head, however in the code you do use the size of pred_all and not the size of rep_all to down sample, please clarify

**Comment by Yussef93** [comment]
ok, thanks for that, another question can you clarify what is the difference between negative high entropy and negative low entropy ? when to use which mask ?

**Comment by Yussef93** [comment]
Also which type of loss do you use (BCE or anchor_ema or the third option) ?

**Comment by Haochen-Wang409** [comment]
> ok, thanks for that, another question can you clarify what is the difference between negative high entropy and negative low entropy ? when to use which mask ?

The main differences between ```high``` and ```low``` lie in the reliability of predictions from the memory bank, which will be served as negative samples in computing contrastive loss.
For all our experiments, we use ```high_entropy_mask```, and we just provide this option for follow-up researchers to reproduce the ablation study (Table 4 in the paper).

> Also which type of loss do you use (BCE or anchor_ema or the third option) ?

We neither use BCE nor anchor_ema in our experiments. These two alternatives are also for ablations.

**Comment by jannehlamin** [comment]
Thank for the paper and the project. In my situation, I have only three class of objects but the training, the contrastive loss always return 0.0000. why?

**Comment by Haochen-Wang409** [comment]
As you can see in the [config.yaml](https://github.com/Haochen-Wang409/U2PL/blob/main/experiments/pascal/1464/ours/config.yaml#L46), the ```low_rank``` equals to 3, which is too large for 3 or 2 classes dataset.

You could change it to 1.

**Comment by jannehlamin** [comment]
Thanks for the insight .
