### ISSUE TITLE
类别负样本内存库中的特征绘制

### ISSUE THREAD

**Issue by NJNUCS** [Haochen-Wang409/U2PL#84]
您好，谢谢您宝贵的贡献，阅读过您的文章之后，我想知道图3中的内存库中保存各个类别对应的负样本的特征是怎么画出来的呀，谢谢

**Comment by Haochen-Wang409** [comment]
我们使用的是 PPT 里面的 “三维旋转” 功能

**Comment by NJNUCS** [comment]
您好，我就是想问这个负样本浅蓝色的格调是怎么弄出来的呀，



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Haochen ***@***.***&gt;; 
发送时间: 2022年9月6日(星期二) 上午9:46
收件人: ***@***.***&gt;; 
抄送: "완 \(ˆoˆ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Haochen-Wang409/U2PL] 类别负样本内存库中的特征绘制 (Issue #84)





 
我们使用的是 PPT 里面的 “三维旋转” 功能

**Comment by Haochen-Wang409** [comment]
首先把 reliable pixels 那张图片进行删除背景，把白色区域删除。然后选择图片或纹理填充该图片
