### ISSUE TITLE
About some settings of constant params

### ISSUE THREAD

**Issue by DISAPPEARED13** [Haochen-Wang409/U2PL#85]
Hi, there.
I notice that the constant number like the number of anchor pixels, negative samples, like in yaml, setting as 256 and 50. Could you please tell me how you calculated these numbers? Are they based on the input size?

Thanks alot!

**Comment by Haochen-Wang409** [comment]
Hi, thanks for your attention of our work.

We simply obtained these two hyper-parameters from ReCo [ICLR 2021]: https://github.com/lorenmt/reco
It is better to ablate these two parameters if you want to apply our U<sup>2</sup>PL to new datasets.

**Comment by DISAPPEARED13** [comment]
Thanks for suggestions! :)
