### ISSUE TITLE
消融实验

### ISSUE THREAD

**Issue by unrealMJ** [Haochen-Wang409/U2PL#86]
![image](https://user-images.githubusercontent.com/45420156/190885807-e9cc0f33-3355-4528-9f59-8285b90a3f0c.png)

您好，请问这里的第一行对于teacher模型给出的伪标签是直接使用的，没有设置0.95这样的阈值是吗？

**Comment by Haochen-Wang409** [comment]
第一行是 Mean Teacher.

在我们的实验中，都没有设置 0.95 这样的固定 confidence 阈值，而是用 80% 低熵的预测作为 pseudo-label
