### ISSUE TITLE
Questions about the ablation study in table6

### ISSUE THREAD

**Issue by HeimingX** [Haochen-Wang409/U2PL#9]
Hi, thanks for the awesome work. 

I have a question about the ablation study part. In table 6, Dynamic Partition Adjustment (DPA) and high entropy filtering (Unreliable) are ablated. For me, the Unreliable component means the pseudo-label generation process in Eq.(6) and the DPA component means the threshold dynamic adjusment process in Eq.(7). So it means the use of DPA should be based on the use of Unreliable component. However, I found the penultimate row of table 6 shows the result for a method w/ DPA and w/o Unreliable. It is weird to me and I am not sure if my understanding is correct or not.

**Comment by Haochen-Wang409** [comment]
Hi, thanks your approval for our work.

Actually, ```Unreliable``` in Tab. 6 **does not** mean filtering out unreliable psedu-labels for supervision which is mentioned in Eq. (6). It means whether to regard **unrealible pixels as negative samples** in contrastive loss or not, which is explained in Tab. 4. In other words, if w/ Unreliable, $z_{cij}^{-}$ in Eq. (4) are all unreliable pixels.

**Comment by HeimingX** [comment]
Hi, thanks for your answer and my question is well solved.
