### ISSUE TITLE
Cityscapes Result

### ISSUE THREAD

**Issue by Ziwei-Niu** [Haochen-Wang409/U2PL#92]
Hi, I am really interested in your paper and it's a great work. But when I try to reproduce the result on cityscapes dataset using Multiple Gpus, I meet a bug:
<img width="1159" alt="99f058eae8fa07a73f98f5ade6022a2" src="https://user-images.githubusercontent.com/53245939/195871334-395f1b77-809b-4495-bfea-9d107ef8039c.png">
And I looked up this error online and found that it was caused by an array crossing the bounds,  I checked the code and found the code below  in loss_helper.py may cause this issue:
![image](https://user-images.githubusercontent.com/53245939/195873354-cc33b275-8c85-4976-b198-3959ea775eb1.png)

But I have no idea how to fix it , I will appreciate it if you give me some advice, thank you.

**Comment by Haochen-Wang409** [comment]
Hi, thanks for your attention of our work!

This code seems to belong to ```OHEM```, which is simply borrowed from [AEL](https://github.com/hzhupku/SemiSeg-AEL).

You could try turning off ```OHEM``` in ```config.yaml```.
