### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DeepHM** [Haochen-Wang409/U2PL#94]
Hello.
Can you share your research model trained in PASCAL-VOC?
And what is AEL in your paper?

thank you

**Comment by Haochen-Wang409** [comment]
Did you encounter any problems in reproducing the results?

AEL is a great work published in NeurIPS 2021. 
https://proceedings.neurips.cc/paper/2021/file/b98249b38337c5088bbc660d8f872d6a-Paper.pdf

**Comment by DeepHM** [comment]
Hello.
I am doing some research on semi-supervised semantic segmentation.

Just to confirm some of your nice research, I could check through reproduction but just wanted to ask if PACAL-VOC is also shareable as you shared Checkpoints from Cityscapes for quick verification.

Thank you!

**Comment by Haochen-Wang409** [comment]
Checkpoints can be found [here](https://drive.google.com/drive/folders/1_BcixhrEqJEMo3lzKTKPJ_7gCWEjUBWp).

**Comment by DeepHM** [comment]
Oh, thank you so much!

Good luck!
