### ISSUE TITLE
Questions about Augmented PASCAL-VOC2012

### ISSUE THREAD

**Issue by DeepHM** [Haochen-Wang409/U2PL#95]
As with the use of the Augmented PASCAL-VOC2012 dataset in other semi-supervised semantic segmentation studies (i.e., CPS, PS_MT) , I would like to reproduce your study in 1/8 (1323) of the Augmented PASCAL-VOC. However, it seems to me that this github is training code from Full(1464). Any code that trains on 1/8 (1323) of Augmented PASCAL-VOC? Or is it possible by simply changing the options in the 'config.yaml' file?

**Comment by Haochen-Wang409** [comment]
Just change the ```data_list``` and ```n_sup``` in ```config.yaml```.

**Comment by DeepHM** [comment]
Thank you !

**Comment by DeepHM** [comment]
Hello.
PASCAL_VOC does not contain "eval.sh".
How can I do this?

**Comment by Haochen-Wang409** [comment]
There is no need to run ```eval.sh``` for PASCAL-VOC experments.
The performance has been reported during training.

While for Cityscapes, we apply slide window evaluation follow previous SOTA AEL, and thus ```eval.sh``` is necessary.

**Comment by DeepHM** [comment]
Thank you !!

**Comment by DeepHM** [comment]
Hello.
Can I know the gpu information (name and number of gpu) and training time in your experiments?

If possible, I would like to know VOC and Cityscapes roughly.
(especially training time)

Thank you !

**Comment by Haochen-Wang409** [comment]
Please refer to **Note** section of README.

**Comment by DeepHM** [comment]
oh.. thank you!

**Comment by DeepHM** [comment]
Hello.
In your paper, the study only appears to have the model trained with Resnet101.

If you have a model trained with Resnet50 on PASCAL VOC2012, can you please share? 
(model file with Resnet50 in PASCAL VOC2012)

**Comment by Haochen-Wang409** [comment]
We did not train R50 for any datasets.

**Comment by DeepHM** [comment]
Thanks for your kind reply.
