### ISSUE TITLE
About checkout model of cityscapes 

### ISSUE THREAD

**Issue by MRtianyanxiaobai** [Haochen-Wang409/U2PL#97]
作者您好，我在使用您所给的checkout时遇见了问题。我将您给的预训练模型 city_744_AEL_U2PL_78.51.pth 放在了 `U2PL/experiments/cityscapes/744/ours/checkpoints` 下，并且修改名字为 ckpt.pth 
然后运行出现错误如下，应该是预训练模型中没有这两个字段：
![image](https://user-images.githubusercontent.com/33564577/200504009-83fa2efe-0814-4507-b2aa-64cdeacad875.png)

**Comment by Haochen-Wang409** [comment]
您可以在 [这一行](https://github.com/Haochen-Wang409/U2PL/blob/main/eval.py#L123) 之前加一句：
```checkpoint = {'model_state': checkpoint}```

**Comment by MRtianyanxiaobai** [comment]
ok，问题已解决，谢谢作者大大
