### ISSUE TITLE
About the "All" and the "plain Lc"

### ISSUE THREAD

**Issue by yasuobinggan** [Haochen-Wang409/U2PL#99]
Amazing work!
I want to ask the "All" in table4 and the "plain Lc" in figure4 are the same thing?
Thank you very much! Looking forward to your reply.
![image](https://user-images.githubusercontent.com/30293157/203323862-7ddda74c-7e75-4610-8e41-4b90133d0577.png)
![image](https://user-images.githubusercontent.com/30293157/203324078-d0524bcd-4e22-4df6-bbff-6f5bfb1e6d2a.png)

**Comment by Haochen-Wang409** [comment]
Thanks for your attention and approval of our work.

Yes, they are the same, which means vanilla contrastive learning is used. In fact, Tab. 4 verified our motivation: using **unreliable** pseudo-labels in semi-supervised semantic segmentation is crucial

**Comment by yasuobinggan** [comment]
Thank you again!
